# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "2.4"
name = "Tyvek-Soft-Facemask"
repo = "https://www.thingiverse.com/thing:4257706?fbclid=IwAR3kf1TPndvgbJBko3u5LhUB-mfFUCDu01khFlNCN21vBMrifof3LLYPakg#google_vignette"
version = "2.0.0"
license = "CC-BY-4.0"
licensor = "Mark Gaponoff <https://www.thingiverse.com/boring_pilot/designs>"
function = "Tyvek mask body with 3DP filter attachments."
documentation-language = "en-US"
organization = "National Institute of Allergy and Infectious Diseases"
readme = "https://3d.nih.gov/entries/download/13519/2"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "A41D 13/11"
tsdc = "3DP"
bom = "https://3d.nih.gov/api/submissions/17480/files/input/387117"
manufacturing-instructions = "https://3d.nih.gov/api/submissions/17480/files/input/387117"
source = [
     "https://3d.nih.gov/api/submissions/17480/files/input/387131",
     "https://www.thingiverse.com/download:7922388",
     "https://www.thingiverse.com/download:7922388",
     "https://www.thingiverse.com/download:7939884",
     "https://www.thingiverse.com/download:7993815",
     "https://www.thingiverse.com/download:8109926",
     "https://www.thingiverse.com/download:8164725",
     "https://www.thingiverse.com/download:7922389",
     "https://www.thingiverse.com/download:8109930",
     "https://3d.nih.gov/entries/3DPX-013519"
]

[[image]]
location = "https://3d.nih.gov/images/niaid-logo-white.svg"
slots = [
  "logo",
]
tags = [
  "logo",
]

[[image]]
location = "https://3d.nih.gov/api/submissions/17480/files/input/387118"
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]

[[image]]
location = "https://3d.nih.gov/api/submissions/17480/files/input/387122"

[[image]]
location = "https://3d.nih.gov/api/submissions/17480/files/input/387128"

[[image]]
location = "https://3d.nih.gov/api/submissions/17480/files/input/387133"

[[image]]
location = "https://3d.nih.gov/api/submissions/17480/files/input/387123"
