# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Flexible-Goggles"
repo = "https://www.printables.com/model/59044-flexible-goggles-optimised-for-3dp-print-on-transp"
license = "CC BY 4.0"
licensor = "iczfirz <https://www.printables.com/@iczfirz>"
function = "Features TPU and no nozzle travel or material oozing. Design hugs the face to create a seal, which is more protective than a simple eye shield."
documentation-language = "en-GB"
organization = "Printables"
# In the case of no releases, can link to the latest commit.
release = "https://gitlab.com/YOU/your-awesome-project/-/releases/1.0.0"
readme = "README.md"
contribution-guide = "CONTRIBUTING.md"
image = [
  # logo
  "imgs/xxx.jpg",
  # product-photo
  "imgs/yyy.jpg"
]
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
attestation = "https://certification.oshwa.org/cl000001.html"
publication = "https://doi.org/10.1371/journal.pone.0193087"
# A Cooperative Patent Classification-ID, describing this projects hardware; You may want to search for it here: <https://worldwide.espacenet.com/classification>
cpc-patent-class = "A41D 13/11"
tsdc = "MEC/ASM/etc." # Void if there is no valid licence. Possible values for the project listed here: https://gitlab.com/OSEGermany/oh-tsdc/-/blob/master/OH-TsDC.md?ref_type=heads.
bom = "BoM.csv"
manufacturing-instructions = "Documentation/Assembly_Guide/AssemblyGuide.md"
user-manual = "Documentation/User_Guide/UserGuide.md"
# Sources for the parts information
source = [
     "main.scad",
     "part_a.scad",
     "part_b.scad",
     "params.csv"
     ]
# Any mass always has to be in g (gramms)
mass= 50330.0

[outer-dimensions]
# Any dimension value always has to be in [mm] (milli-meters). Need all 3.
width = 400
depth = 350
height = 150

[[software]]
release = "https://github.com/arduino/ArduinoCore-mbed/releases/tag/1.3.2"
installation-guide = "https://github.com/arduino/ArduinoCore-mbed/blob/a2c06d768f5ebb6821ae6505b2032ee58f4ef70d/README.md"
