# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "PUC-Rio_Oculos_de_Protecao"
repo = "https://drive.google.com/drive/folders/1O5yAkDuu6TZSS_KA0XeO9hOJu2UZJwbH?sort=13&direction=a"
license = "Creative Commons Attribution-Noncommercial 4.0"
licensor = "João Azevedo <jvictor@puc-rio.br>"
function = "Fabrication instructions are in Brazilian Portuguese. Eye shield design featuring a 3DP frame and clear plastic shield."
documentation-language = [
   "pt",
   "en"
]
organization = "PUC Rio"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "A61F 9/02"
tsdc = "LAS" 
manufacturing-instructions = "https://drive.google.com/file/d/1iHtWDPP4ZIEaeqv8QEy2K-sorJ1wv2LR/view?usp=sharing"
user-manual = "https://drive.google.com/file/d/14b_138uSURZKQ7Gtq6lu93b_CaXOL1GA/view?usp=sharing"
source = [
     "https://drive.google.com/file/d/1G_XlEMnq81TdeHrJpyzXSfNLRHsHyB-I/view?usp=sharing",
     "https://drive.google.com/file/d/1RI4VIo68Qh6xKe-uH22xaRX3yRvX_PrG/view?usp=sharing",
     "https://drive.google.com/file/d/1OGE8K72Zx6qrVrunPSiczlzCyR71CffM/view?usp=sharing",
     "https://drive.google.com/file/d/1cLSmJ-bsmWHlfJRrg5CTyUBm0nO-1lZF/view?usp=sharing",
     "https://drive.google.com/file/d/1unxi7tioBG3oEFCAy3-sX9PkAnRVHpB-/view?usp=sharing"
     ]
