# SPDX-FileCopyrightText: 2024 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "your-awesome-OSH"
repo = "https://gitlab.com/YOU/your-awesome-project/"
version = "1.0.0"
# If none listed, delete line. The value needs to be a valid SPDX [License Expression](https://spdx.github.io/spdx-spec/v2-draft/SPDX-license-expressions/). Usually that is a single SPDX license ID, foudn in the "Identifier" column in this table: https://spdx.org/licenses/
license = "AGPL-3.0-or-later"
licensor = "Joel Doe <joel.doe@example.com>"
function = "This thng can clean, fly to the moon, keep you warm when its freezing, transplant an organ on its own, ..."
documentation-language = "en-GB"
organization = "xxx"
release = "https://gitlab.com/YOU/your-awesome-project/-/releases/1.0.0"
readme = "README.md"
contribution-guide = "CONTRIBUTING.md"
image = [
  # logo
  "imgs/xxx.jpg",
  # product-photo
  "imgs/yyy.jpg"
]
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
attestation = "https://certification.oshwa.org/cl000001.html"
publication = "https://doi.org/10.1371/journal.pone.0193087"
standard-compliance = "DIN EN 1335" # Void if there is no valid license. DIN SPEC 1305-1 if covers all areas, or DIN SPEC 1305-2 if officially listed.
# A Cooperative Patent Classification-ID, describing this projects hardware; You may want to search for it here: <https://worldwide.espacenet.com/classification>
cpc-patent-class = "D03D 35/00"
tsdc = "MEC/ASM/etc." # Void if there is no valid licence. Possible values for the project listed here: https://gitlab.com/OSEGermany/oh-tsdc/-/blob/master/OH-TsDC.md?ref_type=heads.
bom = "BoM.csv"
manufacturing-instructions = "Documentation/Assembly_Guide/AssemblyGuide.md"
user-manual = "Documentation/User_Guide/UserGuide.md"
# Sources for the parts information
source = [
     "main.scad",
     "part_a.scad",
     "part_b.scad",
     "params.csv"
     ]
# Any mass always has to be in g (gramms)
mass= 50330.0

[outer-dimensions]
# Any dimension value always has to be in [mm] (milli-meters)
width = "400"
depth = "350"
height = "150"

[[software]]
release = "https://github.com/arduino/ArduinoCore-mbed/releases/tag/1.3.2"
installation-guide = "https://github.com/arduino/ArduinoCore-mbed/blob/a2c06d768f5ebb6821ae6505b2032ee58f4ef70d/README.md"
