# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "2.4"
name = "your-awesome-OSH"
repo = "https://gitlab.com/YOU/your-awesome-project/"
license = "AGPL-3.0-or-later"
licensor = "Joel Doe <joel.doe@example.com>"
function = "This thing can clean, fly to the moon, keep you warm when its freezing, transplant an organ on its own, ..."
documentation-language = "en-GB"
version = "1.0.0"
organization = "xxx"
release = "https://gitlab.com/YOU/your-awesome-project/-/releases/1.0.0"
readme = "README.md"
contribution-guide = "CONTRIBUTING.md"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
attestation = "https://certification.oshwa.org/cl000001.html"
publication = "https://doi.org/10.1371/journal.pone.0193087"
standard-compliance = "DIN EN 1335"
cpc-patent-class = "A41D 13/11"
tsdc = "MEC/ASM/etc."
bom = "BoM.csv"
manufacturing-instructions = "Documentation/Assembly_Guide/AssemblyGuide.md"
user-manual = "Documentation/User_Guide/UserGuide.md"
# Sources for the parts information
source = [
     "main.scad",
     "part_a.scad",
     "part_b.scad",
     "params.csv"
     ]
mass = 50330.0

[outer-dimensions]
width = 400
depth = 350.8
height = 150

[[software]]
release = "https://github.com/arduino/ArduinoCore-mbed/releases/tag/1.3.2"
installation-guide = "https://github.com/arduino/ArduinoCore-mbed/blob/a2c06d768f5ebb6821ae6505b2032ee58f4ef70d/README.md"

[[image]]
location = "imgs/xxx.jpg"
# "depicts" contains a text that explains what can be seen on the image.
depicts = "The logo of this OSH project"
# Possible values for slots:
# <https://github.com/iop-alliance/OpenKnowHow/blob/c4ba79b41f0c87993418a2862c9ad17b246224ee/src/schema/okh.schema.json#L248>
slots = [
  "logo",
]
tags = [
  "logo",
]

[[image]]
location = "imgs/yyy.jpg"
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]

[[image]]
location = "imgs/xxx.jpg"
