# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Blivande-Makerspace-Disposable-Gown"
repo = "https://forum.blivande.com/t/5-can-you-share-your-blueprints-and-instructions/910"
version = "0.9"
license = "CC-BY-SA-4.0"
licensor = "Hugi Asgeirsson <https://forum.blivande.com/u/hugi/summary>"
function = "Disposable gown design using plastic sheeting and heat sealed seams. Other plastic-based fabrics could be substituted. This gown has been designed for use in international communities. US-based medical facilities may require different gown folding and packaging."
documentation-language = [
   "en",
   "sv",
   "fr",
   "es",
   "ar"
]
organization = [
   "Blivande",
   "Stockholm Makerspace"
]
readme = "https://forum.blivande.com/t/4-can-you-share-your-blueprints-and-instructions/910"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "A41D 13/00"
tsdc = "ASM"
bom = "https://docs.google.com/presentation/d/1IOtvYWFO4dKMyPfz-TLTUut4PyG82EkKAenLN1n0k7w/edit#slide=id.g733b296232_0_274"
manufacturing-instructions = "https://docs.google.com/presentation/d/1IOtvYWFO4dKMyPfz-TLTUut4PyG82EkKAenLN1n0k7w/edit#slide=id.g733b296232_0_274"
source = [
     "https://drive.google.com/file/d/1ONn7R6OB15RSYnlGKQajlf0uvp8R8lhk/view",
     "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/ABoHhM2Yqu95E0zuHa1Qkfs/Current%20Version/09?preview=09.ai&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=bjzhyl5w&dl=0",
     "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/ABoHhM2Yqu95E0zuHa1Qkfs/Current%20Version/09?preview=09B.ai&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=wklp79di&dl=0",
     "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AJoYzJOSuvM2QsjJs3afrW0/Current%20Version/Fl%C3%A4rpit?preview=Fl%C3%A4rpit.ai&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=lotwiv78&dl=0",
     "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AJoYzJOSuvM2QsjJs3afrW0/Current%20Version/Fl%C3%A4rpit?preview=Fl%C3%A4rpit.dxf&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=z5ugdf8r&dl=0",
     "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AJoYzJOSuvM2QsjJs3afrW0/Current%20Version/Fl%C3%A4rpit?preview=Fl%C3%A4rpitA.ai&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=xtv5ajb9&dl=0",
     "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AJoYzJOSuvM2QsjJs3afrW0/Current%20Version/Fl%C3%A4rpit?preview=Fl%C3%A4rpitA.dxf&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=2lhrxmi1&dl=0",
     "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AJoYzJOSuvM2QsjJs3afrW0/Current%20Version/Fl%C3%A4rpit?preview=Fl%C3%A4rpitB.ai&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=4iy8i6qo&dl=0",
     "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AJoYzJOSuvM2QsjJs3afrW0/Current%20Version/Fl%C3%A4rpit?preview=Fl%C3%A4rpitB.dxf&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=g1rchx1k&dl=0",
     "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AJoYzJOSuvM2QsjJs3afrW0/Current%20Version/Fl%C3%A4rpit?preview=Instruktion+Fl%C3%A4rpigt+Visir.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=ka73wo8b&dl=0"
]

[[image]]
location = "https://forum.blivande.com/uploads/blivande/original/1X/32041100f3d25f6810def2487dd4b11b0c3ba619.png"
slots = [
  "logo",
]
tags = [
  "logo",
]

[[image]]
location = "https://forum.blivande.com/uploads/blivande/optimized/1X/be93cc7b09d04f6639b37d103708ff1f3c102297_2_517x291.jpeg"
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/ACQMatL_WfUGxxF9MsuCI8I/Pictures/0.6%20Faster%20to%20make%2C%20without%20drip%20protection?preview=IMG_20200327_143911.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=rirzzhmc&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/ACQMatL_WfUGxxF9MsuCI8I/Pictures/0.6%20Faster%20to%20make%2C%20without%20drip%20protection?preview=IMG_20200327_144413.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=94h8kh0n&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/ACQMatL_WfUGxxF9MsuCI8I/Pictures/0.6%20Faster%20to%20make%2C%20without%20drip%20protection?preview=IMG_20200327_144417.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=lqpc1n7y&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/ACQMatL_WfUGxxF9MsuCI8I/Pictures/0.6%20Faster%20to%20make%2C%20without%20drip%20protection?preview=IMG_20200327_144437.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=sw4v1kck&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/ACQMatL_WfUGxxF9MsuCI8I/Pictures/0.6%20Faster%20to%20make%2C%20without%20drip%20protection?preview=IMG_20200327_144507.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=upjos664&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/ACQMatL_WfUGxxF9MsuCI8I/Pictures/0.6%20Faster%20to%20make%2C%20without%20drip%20protection?preview=IMG_20200327_144522.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=obfza067&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/ACQMatL_WfUGxxF9MsuCI8I/Pictures/0.6%20Faster%20to%20make%2C%20without%20drip%20protection?preview=IMG_20200327_144541.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=i7hxg1ws&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/ACQMatL_WfUGxxF9MsuCI8I/Pictures/0.6%20Faster%20to%20make%2C%20without%20drip%20protection?preview=IMG_20200327_150445.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=a7wva1y6&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/ACQMatL_WfUGxxF9MsuCI8I/Pictures/0.6%20Faster%20to%20make%2C%20without%20drip%20protection?preview=VID_20200327_143657.mp4&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=gxjir4bb&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200404_093250.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=yag0baab&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200404_093316.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=o2xrkuay&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200404_093343.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=absx0kvl&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200404_093421.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=xda1nslq&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200404_093502.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=xcljgt7r&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200404_093617.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=5d3k3k3u&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200404_093708.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=k57hj8cl&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200404_093726.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=kb3s9ote&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200404_093919.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=q97ngdpj&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200404_093950.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=gfa5b2ak&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_174819.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=j03jzc9s&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_174840.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=901b56md&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_174858.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=7z652wiz&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_175004.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=woomcxyg&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_175034.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=6qzn5eap&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_175047.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=53k6q30e&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_175105.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=riedx8p8&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_175128.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=nd8mjl32&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_175206.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=xz3ibxsd&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_175234.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=d6u3g6hv&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_175240.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=7cighk3a&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_175320.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=vlgzsv6d&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_175410.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=jto36m9e&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_175509.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=salwuk6w&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_175520.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=gm5nkda0&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_175600.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=kla43a08&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_175607.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=hfmtxbdt&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/AN0duRixmQg6I-VXLLnuvFY/Pictures/0.7%20With%20drip%20protection/Instructiojns?preview=IMG_20200406_175623.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&subfolder_nav_tracking=1&st=qa3j3h6q&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/APq49pkhyjpBeegpF0DHWY8/Pictures?preview=IMG_20200327_144306.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&st=5ej8eelb&dl=0"

[[image]]
location = "https://www.dropbox.com/scl/fo/4yhrrm9vh35p3q2e5h14w/APq49pkhyjpBeegpF0DHWY8/Pictures?preview=Instruktion+Visir+-+Hold+On+0.7.jpg&rlkey=y601g1jlsmm48qmv2mi6enjc2&st=kjyhc4ta&dl=0"
