# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Hela-Disposable-Gown"
repo = [
   "https://drive.google.com/drive/u/2/folders/1FRvMs0q8EPllUBijbE52-wXz7ee4fI-T",
   "https://drive.google.com/drive/u/2/folders/13pir2QUJzeY57lpPxIg0RNzn3Pe7jH3z"
]
license = "LicenseRef-NOASSERTION"
licensor = "Licensor <acrease77@gmail.com>"
function = "This single-use disposable gown is intended for plastic-based fabric such as 1mil or 2mil plastic sheeting and non-woven polypropylene. It is based on the most commercially accepted isolation gown patterns from Medline, Kimberly Clark, and Cardinal Health. This design has been specially modified to improve staff wearability by thumbhole adjustment and increasing the underarm fabric area. Use the Folding Guide and Folding Board to prep your gowns correctly for staff, i.e. they must be folded this way so staff insert their hands into the interior sleeve area when opening a gown package. This is a very important step. Use the Instructable to map out a production line for several different fabric widths, equipment and pattern choices, including a slide presentation for a CNC template. Use the gown sticker as inspiration for making your own organization graphic to label packaged gowns for delivery."
documentation-language = "en"
organization = "Artisan's Asylum"
readme = "https://docs.google.com/presentation/d/15LN2LdpVNr3e97bzGu_QnCeH0d-MGcoZg0qh4-sERr4/edit#slide=id.g840455246b_3_73"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-2"
cpc-patent-class = "A41D 13/00"
# tsdc = "MEC/ASM/etc." 
bom = "https://docs.google.com/presentation/d/15LN2LdpVNr3e97bzGu_QnCeH0d-MGcoZg0qh4-sERr4/edit#slide=id.g840455246b_3_92"
manufacturing-instructions = "https://docs.google.com/presentation/d/15LN2LdpVNr3e97bzGu_QnCeH0d-MGcoZg0qh4-sERr4/edit#slide=id.g773b98fb06_4_48"
user-manual = [
   "https://docs.google.com/drawings/d/14m88r0c_f0jSarDmjAIkSzUiMS9q_-zHNLmjZ9x1Xck/edit",
   "https://docs.google.com/presentation/d/1AcHc38JF_K2F2qFvLRbYQxInHxNEOUm85HWeBdthkvU/edit#slide=id.g779b2e1910_0_1",
   "https://docs.google.com/presentation/d/1BGiY0c5rjdHayHW6kzTgYNV4468ZnaTJVbMVGQFYnhA/edit#slide=id.g73a5c37802_0_3"
]
source = [
     # Size XL
     "https://drive.google.com/file/d/1pb9jeAHjdhiYUA3GxOYzD-yeoTrB8bVL/view?usp=sharing",
     "https://drive.google.com/file/d/1pxVx1Jv78_1WCcbKYDPD3wplzS7ehPl4/view?usp=sharing",
     "https://drive.google.com/file/d/1GppcqYeDCoI0xPhq8RlKP1XnroKxDMfi/view?usp=sharing",
     "https://drive.google.com/file/d/19obIOVsUYhCCtEAJ_7_GhLqR1b32LJxZ/view?usp=sharing",
     "https://drive.google.com/file/d/1nL6ZYIY8F86FiPnSYdkYIkjG6RT3jQQN/view?usp=sharing",
     "https://drive.google.com/file/d/1pVt1OqKE7syHOYZ7yjP2aslFQJ1nrJUX/view?usp=sharing",
     "https://drive.google.com/file/d/1q5PazZoGOBS7HYiNVlRnwgEoazvrLTyP/view?usp=sharing",
     "https://drive.google.com/file/d/13WYl3xt0d2MJGNQvhThjbDmul-Ol05pm/view?usp=sharing",
     "https://drive.google.com/file/d/1jNIzoYmhO2j7EoDZYGFCSHx5r98Q5e9R/view?usp=sharing",
     "https://drive.google.com/file/d/1Ma6fkRb3xNsnl6sD5TcDe8wafpK3OuNF/view?usp=sharing",
     "https://drive.google.com/file/d/1PB_yVCsNscbrDJIZ-aIxwOJfmcjBwqdW/view?usp=sharing",
     "https://drive.google.com/file/d/1vszLl_15C3Nd5kzX3voW1LCImOhn-jcH/view?usp=sharing",
     "https://drive.google.com/file/d/1GVUASRXLqriBIX1k9q9QI9sb4_58xcmV/view?usp=sharing",
     "https://drive.google.com/file/d/1UvFZbrS2f4EuJRJUpe57RldpgMKmpvA7/view?usp=sharing",
     # Size Medium
     "https://drive.google.com/file/d/1oWTzKNYRFq5F-WSaCQ-eIlqbgU37FAvg/view?usp=sharing",
     "https://drive.google.com/file/d/1k1MJa0n3LgUjB3dTpyYDp42ODvLvcj5m/view?usp=sharing",
     "https://drive.google.com/file/d/1gQf5HzBpNiMkDDo7h65-NIJRMrWu2VMy/view?usp=sharing",
     "https://drive.google.com/file/d/17uhvW5Qtnxwtu89Qfl412l1tzTs-rJM8/view?usp=sharing",
     "https://drive.google.com/file/d/1zP2pZvOIMfemMmtrhHmT7QUJgydpd1Rr/view?usp=sharing",
     "https://drive.google.com/file/d/1eB_iSltNXx9381Yq_dImroSZMZilrAxo/view?usp=sharing",
     "https://drive.google.com/file/d/1YG7gnDpUX9uzUGsvcCj4syIhT35Q4sQ3/view?usp=sharing",
     "https://drive.google.com/file/d/1-ovKpxb0rOREKyGCZCjKaE1-CIJzxzx7/view?usp=sharing",
     "https://drive.google.com/file/d/1rHuZVqLLdry7HOOF9PB94SoXE4yhNFQo/view?usp=sharing",
     "https://drive.google.com/file/d/1MIf9U6dql68_ryoYljckmEflrseZ64b8/view?usp=sharing",
     "https://drive.google.com/file/d/1efs2F-21IhYayWXFaOat2xBUHgXWkHtB/view?usp=sharing",
     "https://drive.google.com/file/d/10fAg6HUZuOEdhwfr__XAfOYgFY5b7oya/view?usp=sharing",
     "https://drive.google.com/file/d/1QnJqBlwsN8NwTRzwgkWi-5L2O1ykM-GI/view?usp=sharing"
]

[outer-dimensions]
# Based on size XL.
width = 1092.2
depth = 6.35
height = 1524
