# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "2.4"
name = "UW-DFab_Non-Surgical_Disposable_Isolation_Gown_for_Minimal-to-Low_Barrier_Protection"
repo = "https://dfab.uw.edu/covid-19-fabrication/gown-assembly-and-production/"
license = "CC-BY-SA-4.0"
licensor = "Digital Fabrication at UW <dfab@uw.edu>"
function = "Features a CNC vinyl cutter and 2 mil plastic sheeting. Gowns are intended to meet Level 1 & 2 barrier protection requirements. Post-production gown disinfection may be facility specific- always establish expected requirements from the end user."
documentation-language = "en"
organization = "Digital Fabrication at UW"
readme = "https://dfab.uw.edu/covid-19-fabrication/gown-assembly-and-production/#Making_Safe_Gowns"
contribution-guide = "https://dfab.uw.edu/covid-19-fabrication/gown-assembly-and-production/#Credits"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
publication = "https://3d.nih.gov/entries/3dpx-013945"
cpc-patent-class = "A41D 13/00"
tsdc = "ASM"
bom = "https://dfab.uw.edu/covid-19-fabrication/gown-assembly-and-production/#Materials_and_Equipment"
manufacturing-instructions = [
   "https://dfab.uw.edu/covid-19-fabrication/gown-assembly-and-production/#Manufacturing_and_Assembly",
   "https://3d.nih.gov/api/submissions/18128/files/input/395640"
]
user-manual = "https://docs.google.com/presentation/d/1FHbPC-wWSCiDwZbRt9t5fj5RMzlD6ErDfOYIt4qGiek/edit#slide=id.g839cd7963a_0_8"
source = [
     "https://3d.nih.gov/api/submissions/18128/files/input/395637",
     "https://3d.nih.gov/api/submissions/18128/files/input/395638",
     "https://3d.nih.gov/api/submissions/18128/files/input/395642",
     "https://dfab.uw.edu/wp-content/uploads/2020/04/Screen-Shot-2020-04-22-at-9.20.21-AM-1024x743.png"
     ]

[outer-dimensions]
# Dimensions are rough estimates.
width = 1520
depth = 6
height = 2190

[[image]]
location = "https://dfab.uw.edu/wp-content/uploads/2020/07/DFab-Site-Identity-Final-01.png"
slots = [
  "logo",
]
tags = [
  "logo",
]

[[image]]
location = "https://3d.nih.gov/api/submissions/18128/files/input/395641"
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]

[[image]]
location = "https://3d.nih.gov/api/submissions/18128/files/input/395645"

[[image]]
location = "https://dfab.uw.edu/wp-content/uploads/2020/05/20200504_Hospital-Gown-Fabrication-1600-1-1024x683.jpg"

[[image]]
location = "https://dfab.uw.edu/wp-content/uploads/2020/05/20200504_Hospital-Gown-Fabrication-1367-1024x683.jpg"

[[image]]
location = "https://dfab.uw.edu/wp-content/uploads/2020/05/20200504_Hospital-Gown-Fabrication-1464-1024x683.jpg"

[[image]]
location = ""
