# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Makery-Do-it-Yourself:-pick-up-your-pulse-with-your-fingertips"
repo = "https://www.makery.info/en/2014/11/11/bricole-it-yourself-capter-son-pouls-du-bout-du-doigt/"
license = "CC-BY-NC-SA-4.0"
licensor = "Makery <contact@makery.info>"
function = "Not a pulse oximeter but uses the same principles for measuring pulse rate. Potential for calculating o2 saturation if developed further."
documentation-language = [
   "en",
   "fr"
]
organization = "Makery"
readme = "https://www.makery.info/en/2014/11/11/bricole-it-yourself-capter-son-pouls-du-bout-du-doigt/"
image = [
  # logo
  "https://s3-eu-central-1.amazonaws.com/makeryfiles/wp-content/themes/makery/assets/imgs/Makery-logo.svg",
  # product-photo
  "https://i0.wp.com/makezine.com/wp-content/uploads/2011/01/Screen-Shot-2015-04-15-at-1.56.54-PM.png?w=781&ssl=1"
]
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "A61B 5/00"
tsdc = "ASM" 
bom = "https://youtu.be/yADsi5W-Lls"
manufacturing-instructions = "https://youtu.be/yADsi5W-Lls"
source = "https://makezine.com/article/technology/arduino/collins-lab-infrared-heart-sensor/"
