# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Boise-Ear-Saver"
repo = "https://www.thingiverse.com/thing:4271677?fbclid=IwAR0yOkkfHfTb2QZ5xTSNwpIGbObHGEUMbUg9lPveZx3eRPLicuUAJ1PuYsQ"
version = "2.0.0"
license = "CC-BY-4.0"
licensor = "Ron Steele <https://www.thingiverse.com/messages/compose?username=goldmole>"
function = "This design conforms to the top of the head and keeps mask loops away from the ears entirely. The buttons are high enough for thicker mask loop material yet a ball cap or scrub cap can be worn over it without catching on the saver. Version Two brings the lugs inward another ¾” and edits the straps so one is more rounded for the top of the head and the other flatter to sit right above the base of the skull. This allows the mask to be pulled into the face rather than up the nose or down the chin. Laser cut version: PETG sheeting makes a thin, flexible option. The two raised buttons convert to tabs that prove durable for all-day KN95 wear."
documentation-language = "en-US"
organization = "Thingiverse"
release = "https://www.thingiverse.com/make:788172"
readme = "https://www.thingiverse.com/thing:4271677"
image = [
  "https://cdn.thingiverse.com/assets/ca/15/fc/5d/d4/100_4323.JPG",
  "https://cdn.thingiverse.com/assets/05/2d/00/eb/2b/100_4322.JPG",
  "https://cdn.thingiverse.com/assets/ce/e1/fb/a1/07/100_4319.JPG",
  "https://cdn.thingiverse.com/assets/2e/74/cc/72/fe/large_display_boise_ear_saver_on_ender3.jpg"
]
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "A62B 9/04"
tsdc = "3DP"
source = [
     "https://www.thingiverse.com/download:7960165",
     "https://www.thingiverse.com/download:7998912",
     "https://www.thingiverse.com/thing:4271677/files",
     "https://drive.google.com/file/d/1L5PTPN5FupmJHTp8hJSlbx23mQJq3ILA/view?usp=sharing",
     "https://drive.google.com/file/d/1zz1SZ35h52raLDUi9rIsnqUab2N6i4if/view?usp=sharing"
]
