# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "2.4"
name = "Crocheted-Ear-Saver"
repo = "https://www.ravelry.com/patterns/library/sore-ear-savers?fbclid=IwAR3DDcLaEintspyF7kdVQynX00yeff3KJp7n_KGySWJu564b-3Nvf395m5w"
license = "LicenseRef-NOASSERTION"
licensor = "Cuddly Crochet Creations <cuddlycrochetcreatons@gmail.com>"
function = "Crocheted ear coverings. Easy pattern for sewists or fiber crafters to make. Recommend laundering after use."
documentation-language = "en"
organization = "Ravelry"
readme = "https://www.ravelry.com/patterns/library/sore-ear-savers?fbclid=IwAR3DDcLaEintspyF7kdVQynX00yeff3KJp7n_KGySWJu564b-3Nvf395m5w"
technology-readiness-level = "OTRL-2"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "A42B 1/00"
tsdc = "ASM"
bom = "https://www.ravelry.com/patterns/library/sore-ear-savers?fbclid=IwAR3DDcLaEintspyF7kdVQynX00yeff3KJp7n_KGySWJu564b-3Nvf395m5w"
manufacturing-instructions = "https://www.ravelry.com/patterns/library/sore-ear-savers?fbclid=IwAR3DDcLaEintspyF7kdVQynX00yeff3KJp7n_KGySWJu564b-3Nvf395m5w#"

[outer-dimensions]
# Depth estimated.
width = 50.8
depth = 12.7
height = 76.2

[[image]]
location = "https://style-cdn.ravelrycache.com/images/assets/logos/primary.svg"
slots = [
  "logo",
]
tags = [
  "logo",
]
