# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "2.4"
name = "Hello-Sewing-Fabric-Ear-Saver"
repo = "https://hellosewing.com/diy-ear-saver-for-face-masks/?fbclid=IwAR3hj7X3IEGPtUoVIgWxOPbYTyR04gDtl2sQLGWwfLWgJm_zg5z7Yf7O6tU"
license = "LicenseRef-NOASSERTION"
licensor = "Helen Spencer <https://hellosewing.com/about-and-contact/>"
function = "Pattern and video tutorial for fabric ear savers with buttons. These can be customized to a desired length and laundered."
documentation-language = "en"
organization = "Hello Sewing"
readme = "https://hellosewing.com/diy-ear-saver-for-face-masks/?fbclid=IwAR3hj7X3IEGPtUoVIgWxOPbYTyR04gDtl2sQLGWwfLWgJm_zg5z7Yf7O6tU"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-2"
cpc-patent-class = "A62B 18/08"
# tsdc = "MEC/ASM/etc."
bom = "https://hellosewing.com/diy-ear-saver-for-face-masks/?fbclid=IwAR3hj7X3IEGPtUoVIgWxOPbYTyR04gDtl2sQLGWwfLWgJm_zg5z7Yf7O6tU#Supplies_and_tools"
manufacturing-instructions = [
   "https://hellosewing.com/diy-ear-saver-for-face-masks/?fbclid=IwAR3hj7X3IEGPtUoVIgWxOPbYTyR04gDtl2sQLGWwfLWgJm_zg5z7Yf7O6tU#How_To_Sew_Ear_Savers",
   "https://youtu.be/XjaJzRBA1z0"
]

[outer-dimensions]
# Depth estimated, will be however thick the cloth is.
width = 38.1
depth = 0.254
height = 228.6

[[image]]
location = "https://hellosewing.com/wp-content/uploads/hellosewing-logo-lq.jpg"
slots = [
  "logo",
]
tags = [
  "logo",
]

[[image]]
location = "https://hellosewing.com/wp-content/uploads/ear-saver-featured-681x510.jpg"
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]

[[image]]
location = "https://hellosewing.com/wp-content/uploads/ear-savers-finished.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/ear-saver-materials.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/ear-savers-markings.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/ear-saver-sew.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/ear-saver-trim-snip.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/ear-saver-turn-rso.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/ear-saver-pressing.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/ear-saver-topstitch.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/ear-saver-machine-sewing-button.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/ear-guard-hand-sewing-buttons.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/ear-guards-lined-up.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/ear-guard-modelled.jpg"
