# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "2.4"
name = "Mask-Comfort-Strap"
repo = "https://3d.nih.gov/entries/3dpx-013440"
version = "2.0.0"
license = "CC-BY-4.0"
licensor = "bdsearle <https://3d.nih.gov/users/bdsearle>"
function = "This design has been tested clinically and is recommended when constructed without modification."
documentation-language = "en"
organization = "National Institute of Allergy and Infectious Diseases"
readme = "https://3d.nih.gov/entries/3dpx-013440#specs"
image = [
  "https://3d.nih.gov/api/submissions/17348/files/input/385451",
  "https://3d.nih.gov/api/submissions/17348/files/input/385452"
]
technology-readiness-level = "OTRL-2"
documentation-readiness-level = "ODRL-2"
# A Cooperative Patent Classification-ID, describing this projects hardware; You may want to search for it here: <https://worldwide.espacenet.com/classification>
cpc-patent-class = "A62B 18/08"
tsdc = "3DP"
bom = "https://3d.nih.gov/entries/3dpx-013440#printing"
manufacturing-instructions = "https://3d.nih.gov/entries/3dpx-013440#printing"
