# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Bucket-Bubble-Helmet"
repo = "https://www.thingiverse.com/thing:4322023"
version = "1.0.0"
license = "CC0-1.0"
licensor = "Gabriel Campbell <https://www.youtube.com/@gabrielcampbell3911>"
function = "Google Doc instructions and materials list for making a NIV helmet out of a 5 gallon bucket and other common materials. "
documentation-language = "en"
organization = "Gabriel Campbell"
release = "https://www.thingiverse.com/thing:4322023"
readme = "https://youtu.be/d5N5a_Xbq94"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "A42B 3/28"
tsdc = "ASM" 
bom = "https://docs.google.com/document/d/1rbCVR7-T_BNvCizwcVLApYUZ3lg6lk30xCtaZB2-8ds/edit?tab=t.0"
manufacturing-instructions = "https://docs.google.com/document/d/1rbCVR7-T_BNvCizwcVLApYUZ3lg6lk30xCtaZB2-8ds/edit?tab=t.0"
source = [
     "https://www.thingiverse.com/download:8086605",
     "https://www.thingiverse.com/download:8086606",
     "https://www.thingiverse.com/thing:4322023/files"
]
