# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "2.4"
name = "AirAngel-Blade"
repo = "https://www.airangelblade.org/"
version = "1.0.0"
license = "AGPL-3.0-or-later"
licensor = "Air Angel <airangelblade@gmail.com>"
function = "3DP laryngoscope blades in adult and pediatric sizes, with instructions for use with three sizes of flexible endoscopes and two different video systems- Teslong Industrial Endoscope and Android smartphone. Includes cleaning directions and video instructables."
documentation-language = "en"
organization = "Air Angel"
image = [
  "https://static.wixstatic.com/media/cb974d_44ec052cf72d4c25b2054727a07ee476~mv2_d_4719_3181_s_4_2.jpg/v1/fill/w_356,h_241,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/blade%20(1%20of%201).jpg",
  "https://static.wixstatic.com/media/cb974d_9be27229ae3c4a72994c288f4f3c8f32~mv2_d_1632_1224_s_2.jpg/v1/fill/w_323,h_242,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/IMG_2905.jpg",
  "https://static.wixstatic.com/media/cb974d_a8c413223db745b6b181cf396eb918c1~mv2.jpg/v1/fill/w_332,h_241,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/IMG_2872.jpg"
]
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "G02B 6/00"
tsdc = "3DP"
manufacturing-instructions = "https://youtu.be/K1xTJOpgq-g"
user-manual = "https://youtu.be/eHm3mpfUry0"
source = [
     "https://www.airangelblade.org/download-1",
     "https://www.airangelblade.org/iphone",
     "https://www.airangelblade.org/copy-of-teslong-system-1"
]
