# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Lil-Air-Cleaner"
repo = "https://github.com/Edderic/breathesafe/blob/development/python/notebooks/lil-air-cleaner.ipynb"
version = "1.0.0"
license = "GPL-3.0-only"
licensor = "Edderic Ugaddan <edderic@gmail.com>"
function = "Wearable, portable, rechargeable design intended for air cleaning closest to the user, especially for indoor scenarios where a mask can’t be worn (such as a dentist exam). Components include 3DP frame, QT3 HEPA filter, and Arctic P14 fans. Project link describes aerosol capture testing and recommendations for future research."
documentation-language = "en"
organization = "Edderic"
release = "https://github.com/Edderic/breathesafe/commit/ec75dbb40b8738d0fe89c821e3d99c707fce4675"
readme = "https://github.com/Edderic/breathesafe/blob/main/README.md"
contribution-guide = "https://github.com/Edderic/breathesafe/graphs/contributors"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "F24F 1/00"
tsdc = "ASM" 
bom = "https://github.com/Edderic/breathesafe/blob/development/python/notebooks/lil-air-cleaner.ipynb"
manufacturing-instructions = "https://github.com/Edderic/breathesafe/blob/development/python/notebooks/lil-air-cleaner.ipynb"
source = [
     "https://camo.githubusercontent.com/faeb71ed6d7e1628a65f7594147d92784a5b1873438720d44d3d150ad0b077f5/68747470733a2f2f63646e2e73686f7274706978656c2e61692f636c69656e742f746f5f776562702c715f676c6f7373792c7265745f696d672c775f313032342f68747470733a2f2f736d61727461697266696c746572732e636f6d2f776f726470726573732f77702d636f6e74656e742f75706c6f6164732f323032322f31322f53637265656e2d53686f742d323032322d31322d32332d61742d332e31382e34302d504d2d31303234783833342e6a7067"
]

[[image]]
location = "https://cdn.prod.website-files.com/679bd6d8e9c2f7d8d67ee78a/67be8b08c6717ab4c8713f59_67b4e8e900474b50d493892a_LILAC.png"
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]
