# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "2.4"
name = "Craft-Passion-Face-Mask"
repo = "https://www.craftpassion.com/face-mask-sewing-pattern/#face-mask-pattern"
license = "LicenseRef-NOASSERTION"
licensor = "Joanne Loh <https://www.craftpassion.com/contact/>"
function = "Popular fitted design featuring optional filter pocket, removable nose wire and multiple sizes with sewing templates. Includes SVG files for Cricut users."
documentation-language = "en"
organization = "Craft Passion"
readme = "https://www.craftpassion.com/face-mask-sewing-pattern/#mv-creation-19-jtr"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-2"
cpc-patent-class = "A41D 13/11"
# tsdc = "MEC/ASM/etc."
bom = "https://www.craftpassion.com/face-mask-sewing-pattern/#mv-creation-19-jtr"
manufacturing-instructions = [
   "https://www.craftpassion.com/face-mask-sewing-pattern/#mv-creation-19-jtr",
   "https://www.craftpassion.com/recycle-tutorial-making-of-t-shirt-yarn/"
]
source = [
     "https://www.craftpassion.com/wp-content/uploads/2013/08/face-mask-template-rev3-300x300.png.webp",
     "https://www.craftpassion.com/wp-content/uploads/2013/08/grid-template-rev3-300x300.png.webp",
   # Ordinary Face Mask Sewing Pattern
     "https://www.craftpassion.com/wp-content/uploads/2013/08/men-face-mask-template-rev3.pdf",
     "https://www.craftpassion.com/wp-content/uploads/2013/08/teenagers-women-face-mask-template-rev3.pdf",
     "https://www.craftpassion.com/wp-content/uploads/2013/08/young-kid-face-mask-template-rev3.pdf",
     "https://www.craftpassion.com/wp-content/uploads/2013/08/small-kids-face-mask-template-rev3.pdf",
     # Pocket Face Mask Sewing Pattern
     "https://www.craftpassion.com/wp-content/uploads/2013/08/men-pocket-face-mask-template-rev3.pdf",
     "https://www.craftpassion.com/wp-content/uploads/2013/08/teenagers-women-pocket-face-mask-template-rev3.pdf",
     "https://www.craftpassion.com/wp-content/uploads/2013/08/young-kid-pocket-face-mask-template-rev3.pdf",
     "https://www.craftpassion.com/wp-content/uploads/2013/08/small-kids-pocket-face-mask-template-rev3.pdf",
     # CRICUT Machine (SVG files)
     "https://www.craftpassion.com/wp-content/uploads/2013/08/Men_SVG.zip",
     "https://www.craftpassion.com/wp-content/uploads/2013/08/Women_Teenagers_SVG.zip",
     "https://www.craftpassion.com/wp-content/uploads/2013/08/Kids_7-12_SVG.zip",
     "https://www.craftpassion.com/wp-content/uploads/2013/08/kids_3-6-SVG.zip",
     # Silhouette Machine (studio3 files)
     "https://www.craftpassion.com/wp-content/uploads/2020/03/Face_Masks_Silhouette.zip"
     ]

[outer-dimensions]
# Estimated based off ordinary men's size template.
width = 254
depth = 50.8
height = 203.2

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/cp-logo@2x.png.webp"
slots = [
  "logo",
]
tags = [
  "logo",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/face-mask-pattern-tutorial-1200-768x960.jpg.webp"
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/face-mask-with-nose-wire-1200-735x919.jpg.webp"
tags = [
  "photo",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/anti-fog-mask-1200-768x960.jpg.webp"
tags = [
  "photo",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/sew-face-mask-size-pattern-1200-600x400.jpg.webp"
tags = [
  "photo",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/wear-face-mask-1200-600x400.jpg.webp"
tags = [
  "photo",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/sew-face-mask-1-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/sew-face-mask-2-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/sew-face-mask-3-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/sew-face-mask-4-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/sew-face-mask-5-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/sew-face-mask-6-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/sew-face-mask-7-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/sew-face-mask-8-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/sew-face-mask-9-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/sew-face-mask-10-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/sew-face-mask-11-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/sew-face-mask-12-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/fm1-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/fm2-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/fm3-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/fm4-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/fm5-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/fm6-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/fm7-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/fm8-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/fm9-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/fm10-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/fm11-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/fm12-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/nose-wire-face-mask-1-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/nose-wire-face-mask-2-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/nose-wire-face-mask-3-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/nose-wire-face-mask-4-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/nose-wire-face-mask-5-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/nose-wire-face-mask-6-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/nose-wire-face-mask-7-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/fm13-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/fm14-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/fm15-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/fm16-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/head-tie-face-mask-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/IMG_20200129_104545-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/IMG_20200129_105219-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/IMG_20200129_104428-800-300x300.jpg.webp"
tags = [
  "assembly",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/face-mask-with-pocket-1200-600x400.jpg.webp"
tags = [
  "assembly",
]
