# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Craft-Passion-Window-Face-Mask"
repo = "https://www.craftpassion.com/windowed-face-mask-sewing-pattern/"
license = "LicenseRef-NOASSERTION"
licensor = "Joanne Loh <https://www.craftpassion.com/contact/>"
function = "Pattern in three sizes including small for children. Clear panel is made from vinyl sheeting."
documentation-language = "en"
organization = "Craft Passion"
readme = "https://www.craftpassion.com/windowed-face-mask-sewing-pattern/"
contribution-guide = "https://www.craftpassion.com/windowed-face-mask-sewing-pattern/#mv-creation-71-jtr"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-2"
cpc-patent-class = "A41D 13/11"
# tsdc = "MEC/ASM/etc." 
bom = "https://www.craftpassion.com/windowed-face-mask-sewing-pattern/#mv-creation-71-jtr"
manufacturing-instructions = "https://www.craftpassion.com/wp-content/uploads/2020/06/windowed-face-mask-pattern-instructions.pdf"
source = "https://www.craftpassion.com/wp-content/uploads/2020/05/windowed-face-mask-pattern.pdf"

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/cp-logo@2x.png.webp"
slots = [
  "logo",
]
tags = [
  "logo",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/2020/05/face-mask-vinyl-window.jpg.webp"
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/2020/05/face-mask-lip-reading.jpg.webp"

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/2020/05/windowed-FM1.jpg.webp"

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/2020/05/windowed-FM2.jpg.webp"

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/2020/05/windowed-FM3.jpg.webp"

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/2020/05/windowed-FM4.jpg.webp"

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/2020/05/windowed-FM5.jpg.webp"

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/2020/05/windowed-FM6.jpg.webp"

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/2020/05/windowed-FM7.jpg.webp"

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/2020/05/windowed-FM8.jpg.webp"

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/2020/05/windowed-FM9.jpg.webp"

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/2020/05/windowed-FM10.jpg.webp"

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/2020/05/windowed-FM11.jpg.webp"

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/2020/05/windowed-FM12-300x225.jpg.webp"

[[image]]
location = "https://www.craftpassion.com/wp-content/uploads/2020/05/windowed-FM13-300x225.jpg.webp"
