# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "EPAM-Continuum-GENTL-Mask"
repo = "https://solutionshub.epam.com/solution/epam-gentl-face-mask"   
version = "2.0.0"
# If none listed, value is LicenseRef-NOASSERTION. The value needs to be a valid SPDX [License Expression](https://spdx.github.io/spdx-spec/v2-draft/SPDX-license-expressions/). Usually that is a single SPDX license ID, foudn in the "Identifier" column in this table: https://spdx.org/licenses/
license = "LicenseRef-NOASSERTION"
licensor = "GENTL Mask <GENTL_Mask@epam.com>"
function = "The non-woven filtered version can be rapidly produced by heat bonding. The sewn fabric version retains the duckbill shape and is useful for wearers with claustrophobia or respiratory conditions where a tight-fitting mask is problematic. This is a full tech pack with instructions for wearing, supplies and construction. See filtration documentation for the 2L and 3L non-woven versions."
documentation-language = "en"
organization = "EPAM Continuum"
release = "https://drive.google.com/file/d/1qUaq8ebHcI862l_TDIAOUIdNPZ2I2Vr1/view?usp=sharing"
readme = [
   "https://epamsolutions.a.bigcontent.io/v1/static/GENTL_Mask_Presentation",
   "https://drive.google.com/drive/folders/1KuoJeEBToZh5dw8I54Ip9GklcJ5swzzV"
]
technology-readiness-level = "OTRL-4"
documentation-readiness-level = "ODRL-2"
cpc-patent-class = "A41D 13/11"
# tsdc = "ASM"
bom = [
   "https://drive.google.com/file/d/17K3ERlPz3osiPQml9F_PGGfSSccKzvng/view?usp=sharing",
   "https://drive.google.com/file/d/1nY8tp2bfkvkrXH8Z7fLKBbdW7QHbS7lF/view?usp=sharing"
]
manufacturing-instructions = [
   "https://epamsolutions.a.bigcontent.io/v1/static/Information_Sheet_3Layer",
   "https://epamsolutions.a.bigcontent.io/v1/static/Assembly_Instructions",
   "https://drive.google.com/file/d/12tLkwZiPgyj7NeeM11CQ21U_FzxI230n/view?usp=sharing"
]
source = "https://drive.google.com/file/d/1YPLij2Gg9vaY2MDloNByDtisHxvED6bA/view?usp=sharing"

[outer-dimensions]
# Dimensions from large size measurements with depth estimated.
width = 293.4
depth = 114.3
height = 114.3

[[image]]
location = "https://classic.cdn.media.amplience.net/i/epammarketplace/GENTL_Logo_Final?w=96&v=596798141487"
slots = [
  "logo",
]
tags = [
  "logo",
]

[[image]]
location = "https://classic.cdn.media.amplience.net/i/epammarketplace/GENTL_Mask_4_resize?fmt=webp&v=596798141487"
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]

[[image]]
location = "https://classic.cdn.media.amplience.net/i/epammarketplace/GENTL_Mask_3_resize?fmt=webp&v=596798141487"

[[image]]
location = "https://classic.cdn.media.amplience.net/i/epammarketplace/GENTL_Mask_2_resize?fmt=webp&v=596798141487"

[[image]]
location = "https://classic.cdn.media.amplience.net/i/epammarketplace/GENTL_Mask_image5_resize?fmt=webp&v=596798141487"

[[image]]
location = "https://classic.cdn.media.amplience.net/i/epammarketplace/Gentl_Mask_image4_resize?fmt=webp&v=596798141487"

[[image]]
location = "https://classic.cdn.media.amplience.net/i/epammarketplace/GENTL_Mask_image6_resize?fmt=webp&v=596798141487"

[[image]]
location = "https://classic.cdn.media.amplience.net/v/epammarketplace/GENTL_Mask_RE_RELEASE_YOUTUBE?fmt=webp&v=596798141487"
