# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "2.4"
name = "Hello-3D-Face-Mask"
repo = "https://hellosewing.com/3d-face-mask-diy/?fbclid=IwAR0lFcHea11VMDZNYNeSL0HXyzDGUkqg4NOHrQetOmOQdI_VJMZrg7su7EI"
license = "LicenseRef-NOASSERTION"
licensor = "Helen Spencer <https://hellosewing.com/about-and-contact/>"
function = "Design stands away from the face and features options for a filter pocket, nose bridge support, and elastic ear loops."
documentation-language = "en"
organization = "Hello Sewing"
readme = "https://hellosewing.com/3d-face-mask-diy/#How_to_make_3d_face_mask"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-2"
cpc-patent-class = "A41D 13/11"
# tsdc = "MEC/ASM/etc."
bom = "https://hellosewing.com/3d-face-mask-diy/#3D_Mask_Supplies_and_tools"
manufacturing-instructions = [
   "https://hellosewing.com/3d-face-mask-diy/#3D_FACE_MASK_INSTRUCTIONS",
   "https://www.youtube.com/watch?v=qjqweGdyDuA"
]
source = "https://deft-designer-6802.ck.page/698a0c7d84"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/hellosewing-logo-lq.jpg"
slots = [
  "logo",
]
tags = [
  "logo",
]

[[image]]
location = "https://hellosewing.com/wp-content/uploads/3d-facemask-featured.jpg"
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]

[[image]]
location = "https://hellosewing.com/wp-content/uploads/IMG_20200629_174436.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/3d-facemask.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/3d-facemask5.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/3d-facemask6.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/3d-facemask9.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/3d-facemask15.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/3d-facemask18.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/3d-face-mask-90degrees.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/3d-facemask20.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/IMG_20200629_175200-1536x1152.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/3d-face-mask-pin1.jpg"
