# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Hello-Sewing-Child-Masks"
repo = "https://hellosewing.com/kids-face-mask-template/?fbclid=IwAR19sHzuef7QBVcyCVJxHxuYXHw-WBkY7mhmT1mmko5OwlR0hPwO4lX7qIs"
license = "LicenseRef-NOASSERTION"
licensor = "Helen Spencer <https://hellosewing.com/about-and-contact/>"
function = "Box pleated, two-layer fabric design with three pattern sizes for children 2 years old to teenager."
documentation-language = "en"
organization = "Hello Sewing"
readme = "https://hellosewing.com/kids-face-mask-template/?fbclid=IwAR19sHzuef7QBVcyCVJxHxuYXHw-WBkY7mhmT1mmko5OwlR0hPwO4lX7qIs#How_to_make_kids_face_mask"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-2"
cpc-patent-class = "A41D 13/11"
# tsdc = "MEC/ASM/etc."
bom = "https://hellosewing.com/kids-face-mask-template/?fbclid=IwAR19sHzuef7QBVcyCVJxHxuYXHw-WBkY7mhmT1mmko5OwlR0hPwO4lX7qIs#Supplies_and_tools"
manufacturing-instructions = [
   "https://youtu.be/LuqJ-T8lij4",
   "https://hellosewing.com/kids-face-mask-template/?fbclid=IwAR19sHzuef7QBVcyCVJxHxuYXHw-WBkY7mhmT1mmko5OwlR0hPwO4lX7qIs#INSTRUCTIONS"
]

[outer-dimensions]
# All estimated.
width = 203.2
depth = 25.4
height = 152.4

[[image]]
location = "https://hellosewing.com/wp-content/uploads/hellosewing-logo-lq.jpg"
slots = [
  "logo",
]
tags = [
  "logo",
]

[[image]]
location = "https://hellosewing.com/wp-content/uploads/kids-face-mask-featured-680x510.jpg"
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]

[[image]]
location = "https://hellosewing.com/wp-content/uploads/kids-face-mask-finished.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/kids-face-mask-materials.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/kids-face-mask-tshirt-ties.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/kids-face-mask-layering.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/kids-face-mask-pinned-marked.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/kids-face-mask-nose-wire.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/kids-face-mask-pleats.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/kids-face-mask21.jpg"

[[image]]
location = "https://hellosewing.com/wp-content/uploads/kids-face-masks-side-view.jpg"
