# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Hello-Sewing-Child-Masks"
repo = "https://hellosewing.com/kids-face-mask-template/?fbclid=IwAR19sHzuef7QBVcyCVJxHxuYXHw-WBkY7mhmT1mmko5OwlR0hPwO4lX7qIs"
license = "LicenseRef-NOASSERTION"
licensor = "Helen Spencer <https://hellosewing.com/about-and-contact/>"
function = "Box pleated, two-layer fabric design with three pattern sizes for children 2 years old to teenager."
documentation-language = "en"
organization = "Hello Sewing"
readme = "https://hellosewing.com/kids-face-mask-template/?fbclid=IwAR19sHzuef7QBVcyCVJxHxuYXHw-WBkY7mhmT1mmko5OwlR0hPwO4lX7qIs#How_to_make_kids_face_mask"
image = [
  # logo
  "https://hellosewing.com/wp-content/uploads/hellosewing-logo-lq.jpg",
  # product-photo
  "https://hellosewing.com/wp-content/uploads/kids-face-mask-featured-680x510.jpg",
  "https://hellosewing.com/wp-content/uploads/kids-face-mask-finished.jpg",
  "https://hellosewing.com/wp-content/uploads/kids-face-mask-materials.jpg",
  "https://hellosewing.com/wp-content/uploads/kids-face-mask-tshirt-ties.jpg",
  "https://hellosewing.com/wp-content/uploads/kids-face-mask-layering.jpg",
  "https://hellosewing.com/wp-content/uploads/kids-face-mask-pinned-marked.jpg",
  "https://hellosewing.com/wp-content/uploads/kids-face-mask-nose-wire.jpg",
  "https://hellosewing.com/wp-content/uploads/kids-face-mask-pleats.jpg",
  "https://hellosewing.com/wp-content/uploads/kids-face-mask21.jpg",
  "https://hellosewing.com/wp-content/uploads/kids-face-masks-side-view.jpg"
]
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-2"
cpc-patent-class = "A41D 13/11"
# tsdc = "MEC/ASM/etc." 
bom = "https://hellosewing.com/kids-face-mask-template/?fbclid=IwAR19sHzuef7QBVcyCVJxHxuYXHw-WBkY7mhmT1mmko5OwlR0hPwO4lX7qIs#Supplies_and_tools"
manufacturing-instructions = [
   "https://youtu.be/LuqJ-T8lij4",
   "https://hellosewing.com/kids-face-mask-template/?fbclid=IwAR19sHzuef7QBVcyCVJxHxuYXHw-WBkY7mhmT1mmko5OwlR0hPwO4lX7qIs#INSTRUCTIONS"
]

[outer-dimensions]
# Based off size large (teens). Depth estimated.
width = 203.2
depth = 76.2
height = 152.4
