# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Jesse-Mask"
repo = "https://www.youtube.com/watch?v=pbqkLcPHhcQ"
license = "LicenseRef-NOASSERTION"
licensor = "Fabric Patch Team <info@fabricpatch.net>"
function = "A shaped, non-pleated mask with multiple pattern sizes for children. The YouTube instructional gives detailed guidance from start to finish- including how to print the pattern, measure a face for appropriate fit, and construction tips."
documentation-language = "en"
organization = "The Fabric Patch"
release = "https://media.rainpos.com/220/jessemask.pdf?fbclid=IwAR3nGQj-91uOVglet0gp4Aakrt2tfk_QPxBpKWv4G-D-ISUTndB2aPvd_c4"
readme = "https://youtu.be/pbqkLcPHhcQ"
image = "https://yt3.googleusercontent.com/ytc/AIdro_kAkEIkQKWyEZDtkLXPV5UvjbtSKEqL3Wk-faEbpScWhV4=s160-c-k-c0x00ffffff-no-rj"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-1"
cpc-patent-class = "A41D 13/11"
# tsdc = "MEC/ASM/etc."
bom = "https://youtu.be/pbqkLcPHhcQ?t=225"
manufacturing-instructions = "https://youtu.be/pbqkLcPHhcQ?t=514"
source = "https://media.rainpos.com/220/jessemask.pdf?fbclid=IwAR3nGQj-91uOVglet0gp4Aakrt2tfk_QPxBpKWv4G-D-ISUTndB2aPvd_c4"

[outer-dimensions]
# Any dimension value always has to be in [mm] (milli-meters). Need all 3.
width = 279.4
depth = 76.2
height = 152.4
