# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "MakeIt-Labs-Fitted-Mask"
repo = "https://www.makeitlabs.com/fittedmask"
license = "CC BY 4.0"
licensor = "MakeIt Labs <info@makeitlabs.com>"
function = "Non-pleated shaped style mask designed for heat sealing construction with non-woven polypropylene. The medium pattern, when printed at 75% and 90%, can be used for children’s masks."
documentation-language = "en"
organization = "MakeIt Labs"
readme = "https://www.makeitlabs.com/fittedmask"
image = [
  # logo
  "https://images.squarespace-cdn.com/content/v1/54e78ccde4b0f93fea044610/1458135215426-MP7GKEBE0DILG6K34SZW/logo-2016-01.png?format=1500w",
  # product-photo
  "https://images.squarespace-cdn.com/content/v1/54e78ccde4b0f93fea044610/1587299904697-TOOL7SCAOM2PIT1DYSL1/MakeIt+Fitted+Mask+FM1.jpg?format=1500w"
]
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "A41D 13/11"
tsdc = "ASM" 
bom = "https://www.makeitlabs.com/fittedmask"
manufacturing-instructions = "https://docs.google.com/a/makeitlabs.com/viewer?a=v&pid=sites&srcid=bWFrZWl0bGFicy5jb218d2lraXxneDoyODIwYWEzMTE3MjZmNGZi"
source = [
     "https://docs.google.com/a/makeitlabs.com/viewer?a=v&pid=sites&srcid=bWFrZWl0bGFicy5jb218d2lraXxneDoxYTJmMTk5OTliMGQyYzVk",
     "https://docs.google.com/a/makeitlabs.com/viewer?a=v&pid=sites&srcid=bWFrZWl0bGFicy5jb218d2lraXxneDo0NzY3Nzg0ZWZlODZjOTI5",
     "https://docs.google.com/a/makeitlabs.com/viewer?a=v&pid=sites&srcid=bWFrZWl0bGFicy5jb218d2lraXxneDoyM2U3NmQ1Y2U2MWRiMWNl",
     "https://docs.google.com/a/makeitlabs.com/viewer?a=v&pid=sites&srcid=bWFrZWl0bGFicy5jb218d2lraXxneDphYTdhNWUxOTYxMGMyMmY",
     "https://sites.google.com/a/makeitlabs.com/wiki/covid-19-projects/covid-19-cloth-masks"
     ]
