# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "TOM-Clearly-Mask"
repo = "https://tomglobal.org/project?id=5ef472c75ea9e13b5a3af2c3"
version = "2.0.0"
license = "LicenseRef-NOASSERTION"
licensor = "Tikkun Olam Makers <hello@tomglobal.org>"
function = "Design based on guidelines from the Israeli Ministry of Health. Features a loop/toggle tie system for easy adjustment. There is a design and user feedback form encouraging community innovation."
documentation-language = "en"
organization = [
   "Tikkun Olam Makers",
   "Poalim for the Community"
]
readme = "https://tomglobal.org/project?id=5ef472c75ea9e13b5a3af2c3"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-2"
cpc-patent-class = "A41D 13/11"
# tsdc = "MEC/ASM/etc." 
bom = "https://tomglobal.org/project?id=5ef472c75ea9e13b5a3af2c3"
manufacturing-instructions = "https://tomglobal.org/project?id=5ef472c75ea9e13b5a3af2c3"
user-manual = "https://tomglobal.org/project?id=5ef472c75ea9e13b5a3af2c3"

[[image]]
location = "https://tomglobal.org/assets/images/tom-logo-color.svg"
slots = [
  "logo",
]
tags = [
  "logo",
]

[[image]]
location = "https://tom-global-dev.s3.eu-west-1.amazonaws.com/misc/poalim.jpeg"

[[image]]
location = "https://tom-prod-new.s3.eu-west-1.amazonaws.com/15.1594290855230.jpg"
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]

[[image]]
location = "https://tom-prod-new.s3.eu-west-1.amazonaws.com/16.1594290870430.jpg"

[[image]]
location = "https://tom-prod-new.s3.eu-west-1.amazonaws.com/IMG_3350%20-%20Copy%20(1).1594290882094.jpg"

[[image]]
location = "https://tom-prod-new.s3.eu-west-1.amazonaws.com/IMG_3351%20-%20Copy%20(1).1594290894273.jpg"

[[image]]
location = "https://tom-prod-new.s3.eu-west-1.amazonaws.com/%D7%AA%D7%94%D7%9C%D7%99%D7%9A%20%D7%A4%D7%99%D7%AA%D7%95%D7%97%20%D7%9E%D7%A1%D7%9B%D7%94%20%D7%A9%D7%A7%D7%95%D7%A4%D7%94.1594454991783.jpg"
