# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "DK-Makers-Face-Shield"
repo = "https://www.thingiverse.com/thing:4347611"
version = "0.7-0.9"
license = "Creative Commons - Attribution"
licensor = "DK_Makers_mod_Corona <https://www.thingiverse.com/dk_makers_mod_corona/designs>"
function = "Design distributed in Denmark with over 100k units produced. The bracket and brow pieces hold the shield in place without hole punching. Version .9 was designed specifically for dental loupes."
documentation-language = [
	"en",
    "da"
]
organization = "Thingiverse"
readme = "https://www.thingiverse.com/thing:4347611#Print%20Settings"
image = [
  "https://cdn.thingiverse.com/assets/dc/25/be/90/a6/large_display_Screenshot_20200409-130151.jpg",
  "https://cdn.thingiverse.com/assets/59/a4/5c/32/4b/large_display_COVID19_Visor-blue-Camera_2.35.jpg",
  "https://cdn.thingiverse.com/assets/97/50/a9/8e/95/large_display_90997296_3130434260351337_962894902843146240_n.jpg",
  "https://cdn.thingiverse.com/assets/9f/9c/c5/99/e4/large_display_Under_print.jpg",
  "https://cdn.thingiverse.com/assets/fa/91/5c/22/b3/large_display_Billede_27.03.2020_09.48.18.jpg"
]
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-2"
cpc-patent-class = "A41D 13/11"
tsdc = "3DP" 
source = [
     "https://cdn.thingiverse.com/assets/aa/f4/66/38/56/large_display_DK_Maker_Visir_0.7.png",
     "https://www.thingiverse.com/thing:4347611/files",
     "https://cdn.thingiverse.com/assets/bb/04/43/06/75/large_display_DK_Maker_Visir_0.9.1.png",
     "https://cdn.thingiverse.com/assets/ba/82/3a/c0/fd/large_display_Dentist_Maker_Shield_0.9.png"
     ]

# [outer-dimensions]
# width = 340
# height = 230
# depth = 0
