# SPDX-FileCopyrightText: 2024 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "DtM_Face_Shield_Headband"
repo = "https://3d.nih.gov/entries/3dpx-013359"
version = "3.1"
license = "Unlicense"
licensor = [
   "Elizabeth Johnson <elizabeth.johansen@olin.edu>",
   "David Packman",
   "Eric Moyer"
]
function = "This PPE is designed specifically for the needs of healthcare workers during the COVID-19 pandemic. It reduces aerosol and splatter exposure and can undergo multiple reuses and cleanings. Additionally, the mask is comfortable and provides ventilation for all-day wear."
documentation-language = "en-US"
organization = [
	"National Institute of Health",
    "design that matters"
]
release = "https://3d.nih.gov/entries/13359/2"
contribution-guide = "https://www.designthatmatters.org/covid-19"
technology-readiness-level = "OTRL-5"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "A41D 13/11"
bom = "https://www.designthatmatters.org/covid-19"
manufacturing-instructions = "https://www.designthatmatters.org/covid-19"
user-manual = "https://www.designthatmatters.org/covid-19"
source = "https://3dprint.nih.gov/discover/3dpx-013359"
mass = 50

[outer-dimensions]
width = 191
height = 52.5
# Listed as 'length' in instructions.
depth = 148.5

[[image]]
location = "https://3d.nih.gov/api/submissions/17230/runs/51edd40a-8c31-47e4-9ce6-f2300fac52f4/output-files/DtM-v_thumb_NIH3D.png"
slots = [
  "logo",
]
tags = [
  "logo",
]

[[image]]
location = "https://images.squarespace-cdn.com/content/v1/5267f3a6e4b0da2bab9939e3/1444954851408-Z8912NHY9U4M5COATKGA/Web+white+logo-01.png"
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]

[[image]]
location = "https://images.squarespace-cdn.com/content/v1/5267f3a6e4b0da2bab9939e3/1585858118343-E7MW3NDJBXSUPXB3OIO0/DtM-v3.0+Face+Shield+PPE+with+NO+LOGO?format=1000w"
