# SPDX-FileCopyrightText: 2024 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Fast-Jungle-Face-Shield"
repo = "https://www.dinalab.net/2020/04/01/face-shield/?fbclid=IwAR2D-qJWqaQI9g6vZVTNsU1ZsHlHttXBVa2l-4ZqQxoZgVJnhpjEeIVAmb0"
version = "1.1"
license = "Creative Commons Attribution-NonCommercial 4.0"
licensor = [
   "General <info@dinalab.net>",
   "Kitty Kelly <kitty@dinalab.net>",
   "Andy Quitmeyer <andy@dinalab.net>"
]
function = "A face shield design requiring little time and materials while still being effective."
documentation-language = "en-US"
organization = "Digital Naturalism Laboratories"
contribution-guide = "https://www.dinalab.net/contact/"
image = [
  # logo
  "https://www.dinalab.net/wp-content/uploads/2019/03/cropped-Digital-Naturalism-Logo_Official_2015-HIGH-resWHITE-1.png",
  # product-photo
  "https://www.dinalab.net/wp-content/uploads/2020/04/image.png",
  "https://www.dinalab.net/wp-content/uploads/2020/04/image-1-768x511.png",
  "https://www.dinalab.net/wp-content/uploads/2020/04/image-3.png",
  "https://www.dinalab.net/wp-content/uploads/2020/04/image-4-768x488.png",
  "https://www.dinalab.net/wp-content/uploads/2020/04/image-2.png"
]
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-2"
cpc-patent-class = "A42B 3/00"
tsdc = "LAS"
bom = "https://www.dinalab.net/2020/04/01/face-shield/?fbclid=IwAR2D-qJWqaQI9g6vZVTNsU1ZsHlHttXBVa2l-4ZqQxoZgVJnhpjEeIVAmb0"
manufacturing-instructions = "https://www.dinalab.net/2020/04/01/face-shield/?fbclid=IwAR2D-qJWqaQI9g6vZVTNsU1ZsHlHttXBVa2l-4ZqQxoZgVJnhpjEeIVAmb0"
user-manual = "https://drive.google.com/drive/folders/1s4lAf2lGYfiGSHjRuez7hnvI0naBTej3"
# Sources for the parts information
source = [
     "https://drive.google.com/drive/folders/1R7S2vxSGS3DLOInkfokaIpI04cGfVeJM",
     "https://drive.google.com/drive/folders/1ics7QAn85BWXv4Swx8NS7M78RyaUqk4T"
     ]

[outer-dimensions]
width = 558.8
height = 254
# Depth not given by the licensor.
# depth = 0
