# SPDX-FileCopyrightText: 2024 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "2.4"
name = "FDS_PAPR"
repo = "https://www.instructables.com/DIY-Powered-Air-Purifying-Respirator-PAPR/"
version = "1.0.0"
license = "CC-BY-NC-SA-4.0"
licensor = "Nathan de Souza <njds337@gmail.com>"
function = "This device is a lightweight powered air-purifying respirator (PAPR) that provides filtered air, face and eye protection, and skin surface cooling."
documentation-language = "en-au"
organization = "Autodesk Instructables"
technology-readiness-level = "OTRL-5"
documentation-readiness-level = "ODRL-3"
# attestation = "NA"
publication = "https://www.instructables.com/DIY-Powered-Air-Purifying-Respirator-PAPR/"
cpc-patent-class = "A41D 13/11"
tsdc = "ASM"
bom = "Cost+of+Materials+11-05-2023.pdf"
manufacturing-instructions = "Documentation/Assembly_Guide/AssemblyGuide.md"
user-manual = "PAPR+Design+Report+2023.pdf"
source = [
     "https://www.instructables.com/DIY-Powered-Air-Purifying-Respirator-PAPR/",
     "https://www.thingiverse.com/thing:5870488#google_vignette",
     "content.instructables.com/FIP/T8AD/LEFORDDR/FIPT8ADLEFORDDR.pdf",
     "content.instructables.com/FEP/P16X/LEFORG20/FEPP16XLEFORG20.pdf",
     "content.instructables.com/FKT/M5PX/LEFORF26/FKTM5PXLEFORF26.pdf"
     ]
mass= 220

[outer-dimensions]
width = 170
height = 240
depth = 210

[[image]]
location = "https://content.instructables.com/FVA/WNDF/LILYUDDY/FVAWNDFLILYUDDY.png"
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]

[[image]]
location = "https://content.instructables.com/FBQ/O9NK/LEE9CN58/FBQO9NKLEE9CN58.png"
tags = [
  "photo",
]

[[image]]
location = "https://content.instructables.com/FKI/LHY5/LEE9CN57/FKILHY5LEE9CN57.jpg"
tags = [
  "photo",
]
