# SPDX-FileCopyrightText: 2024 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "MIT-Curved-Face-Shield"
repo = "https://gitlab.cba.mit.edu/alfonso/curved-face-shield"
version = "3.0.0"
license = "GNU GENERAL PUBLIC LICENSE"
licensor = "Alfonso Parra Rubio <alfonso.parra@cba.mit.edu>"
function = "A PPE face shield that curves to the wearers face for additional coverage."
documentation-language = "en-US"
organization = "Massachussets Institute of Technology"
release = "https://gitlab.cba.mit.edu/alfonso/curved-face-shield/-/commit/794a503ca36c4fc6353b99c6b4ab53778654cb59"
readme = "https://gitlab.cba.mit.edu/alfonso/curved-face-shield/-/blob/master/README.md?ref_type=heads"
image = [
  # product-photos
  "https://gitlab.cba.mit.edu/alfonso/curved-face-shield/-/raw/master/Curved%20Shield%20a5ceaa12053b49cc973e136059016f14/WhatsApp_Image_2020-05-11_at_17.32.00_(1).jpeg",
  "https://gitlab.cba.mit.edu/alfonso/curved-face-shield/-/raw/master/Curved%20Shield%20a5ceaa12053b49cc973e136059016f14/Captura_de_pantalla_2020-05-11_a_las_19.27.05.png",
  "https://gitlab.cba.mit.edu/alfonso/curved-face-shield/-/raw/master/Curved%20Shield%20a5ceaa12053b49cc973e136059016f14/WhatsApp_Image_2020-05-11_at_19.07.07.jpeg",
  "https://gitlab.cba.mit.edu/alfonso/curved-face-shield/-/raw/master/Curved%20Shield%20a5ceaa12053b49cc973e136059016f14/WhatsApp_Image_2020-05-11_at_19.07.08.jpeg",
  "https://gitlab.cba.mit.edu/alfonso/curved-face-shield/-/raw/master/Curved%20Shield%20a5ceaa12053b49cc973e136059016f14/WhatsApp_Image_2020-05-11_at_17.32.00_(5).jpeg",
  "https://gitlab.cba.mit.edu/alfonso/curved-face-shield/-/raw/master/Curved%20Shield%20a5ceaa12053b49cc973e136059016f14/WhatsApp_Image_2020-05-11_at_17.32.00_(3).jpeg",
  "https://gitlab.cba.mit.edu/alfonso/curved-face-shield/-/raw/master/Curved%20Shield%20a5ceaa12053b49cc973e136059016f14/WhatsApp_Image_2020-05-11_at_17.32.00_(4).jpeg"
]
technology-readiness-level = "OTRL-4"
documentation-readiness-level = "ODRL-2"
cpc-patent-class = "A42B 3/00"
tsdc = "LAS" 
# bom = "BoM.csv" No BoM present.
manufacturing-instructions = "https://gitlab.cba.mit.edu/alfonso/curved-face-shield/-/blob/master/README.md?ref_type=heads"
source = [
     "https://gitlab.cba.mit.edu/alfonso/curved-face-shield/-/blob/master/array.png",
     "https://gitlab.cba.mit.edu/alfonso/curved-face-shield/-/blob/master/MIT_CURVED_SHIELD_V3_TEMPORA.dxf",
     "https://gitlab.cba.mit.edu/alfonso/curved-face-shield/-/blob/master/version4.dxf",
     "https://gitlab.cba.mit.edu/alfonso/curved-face-shield/-/blob/master/4feetby8feetArray.dxf",
     "https://gitlab.cba.mit.edu/alfonso/curved-face-shield/-/blob/master/.DS_Store"
     ]

# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Liftup-Face-Shield-with-AutoLock"
repo = "https://www.thingiverse.com/thing:4264137"
license = "Creative Commons - Attribution"
licensor = "Hanoch Hemmerich <https://www.thingiverse.com/hanochh/designs>"
function = "The shield lifts upwards 90 degrees and locks in place. It requires no hole punching."
documentation-language = "en"
organization = "Thingiverse"
image = [
  "https://cdn.thingiverse.com/assets/6f/b2/f5/a7/3d/large_display_liftup_face_shield.jpg",
  "https://cdn.thingiverse.com/assets/f0/a7/73/c6/7b/large_display_of7BA6XO6Q.gif",
  "https://cdn.thingiverse.com/assets/b4/0d/b0/d7/47/large_display_photo_2020-04-05_22-42-07.jpg",
  "https://cdn.thingiverse.com/assets/0f/e5/94/91/8d/large_display_photo_2020-04-05_22-42-26.jpg",
  "https://youtu.be/Mo2_hD4-fRw"
]
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "A42B 3/00"
tsdc = "3DP" 
bom = "https://www.thingiverse.com/thing:4264137"
source = [
     "https://cdn.thingiverse.com/assets/bf/ac/47/a6/ef/medium_preview_Liftup_Face_Shield_part1.png",
     "https://cdn.thingiverse.com/assets/d1/87/38/6d/c9/large_display_3x.png",
     "https://www.thingiverse.com/thing:4264137/files"
     ]
     
# Not given by licensor.
# [outer-dimensions]
# width = 400
# height = 150
# depth = 350
