# SPDX-FileCopyrightText: 2021 Martin Häuer <martin.haeuer@ose-germany.de>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0" # NOT to be changed
name = "VentMon"
repo = "https://github.com/PubInv/ventmon-ventilator-inline-test-monitor"
version = "0.5"
# This needs to be a valid SPDX [License Expression](https://spdx.github.io/spdx-spec/v2-draft/SPDX-license-expressions/). Usually that is a single SPDX license ID, foudn in the "Identifier" column in this table: https://spdx.org/licenses/
license = "CERN-OHL-S-2.0"
licensor = "Robert Read <read.robert@gmail.com>"
function = "VentMon is an open source IoT-enabled spriometer for testing medical ventilators"
documentation-language = "en-US"
organization = "Public Invention"
release = "https://github.com/PubInv/ventmon-ventilator-inline-test-monitor/releases/tag/v0.3.1T"
readme = "https://github.com/PubInv/ventmon-ventilator-inline-test-monitor?tab=readme-ov-file"
contribution-guide = "https://github.com/PubInv/ventmon-ventilator-inline-test-monitor/graphs/contributors"
image = [
  # logo
  "imgs/11892727.png",
  # product-photo
  "imgs/244884512-b96dfc75-58e7-41bd-a88e-ea28e00b7dd8.jpg"
]
technology-readiness-level = "NA"
documentation-readiness-level = "NA"
attestation = "https://certification.oshwa.org/us002353.html"
publication = "https://www.sciencedirect.com/science/article/pii/S2468067221000249"
standard-compliance = "NA"
# A Cooperative Patent Classification-ID, describing this projects hardware; You may want to search for it here: <https://worldwide.espacenet.com/classification>
cpc-patent-class = "NA"
tsdc = "NA"
bom = "VentMon T0.3 BOM.csv"
manufacturing-instructions = "https://github.com/PubInv/ventmon-ventilator-inline-test-monitor/tree/master/design/3dparts"
user-manual = "https://github.com/PubInv/vent-display"
# NOTICE: The below mass below is in grams.
mass=78

[outer-dimensions]
width = "90"
depth = "60"
height = "35"

[[part]]
name = "Housing"
image = "xxx.jpg"
tsdc = "NA"
source = "https://github.com/PubInv/ventmon-ventilator-inline-test-monitor/blob/master/design/3dparts/T0.5/VentMon0.5.scad"
export = [
  "NA.pdf",
  "Case_T0.5.48.stl"
]
# NOTICE: The below mass is a placeholder. Should it be the wt on scad?
mass=2

[part.outer-dimensions]
width = "30"
depth = "60"
height = "55"

[[part]]
name = "Flow Sensor"
image = "xxx.jpg"
tsdc = "NA"
source = "https://github.com/PubInv/ventmon-ventilator-inline-test-monitor/blob/master/design/3dparts/T0.5/VentMon0.5.scad"
export = [
  "NA.pdf",
  "NA.stl"
]
# NOTICE: The below mass is a placeholder. No mass given.
mass=1

# Not sure if the below is correct dimensions based on scad.
[part.outer-dimensions]
id = "10"
t = "1"
x = "50"

[[part]]
name = "PCB"
image = "xxx.jpg"
tsdc = "NA"
source = "https://github.com/PubInv/ventmon-ventilator-inline-test-monitor/blob/master/design/3dparts/T0.5/VentMon0.5.scad"
export = [
  "NA pdf",
  "NA stl"
]
# NOTICE: The below mass is a placeholder. No mass given.
mass=1

[part.outer-dimensions]
# Feather PCB - also Header dimensions, which to reference?
width = "22.9"
length = "50.4"
height = "8.5"

[[part]]
name = "Nozzle"
image = "xxx.jpg"
tsdc = "NA"
source = "https://github.com/PubInv/ventmon-ventilator-inline-test-monitor/blob/master/design/3dparts/T0.5/VentMon0.5.scad"
export = [
  "NA.pdf",
  "Nozzle_T0.5.66.stl"
]
# NOTICE: The below mass is a placeholder. Should it be the wt on scad?
mass=2

[part.outer-dimensions]
id = "10"
t = "1"
x = "40"

[[software]]
release = "https://github.com/PubInv/vent-display/releases/tag/v0.3T"
installation-guide = "https://github.com/PubInv/vent-display"

[[software]]
release = "https://github.com/PubInv/PIRDS-pubinv-respiration-data-standard/releases/tag/v1.3.0"
installation-guide = "https://github.com/PubInv/PIRDS-pubinv-respiration-data-standard"

[[software]]
release = "https://github.com/PubInv/PIRDS-logger/releases/tag/v0.3T"
installation-guide = "https://github.com/PubInv/PIRDS-logger"
# NOTICE: There are no releases for the below software. Page is empty.
[[software]]
release = "https://github.com/PubInv/PIRDS-docker-local/releases"
installation-guide = "https://github.com/PubInv/PIRDS-docker-local"
