# SPDX-FileCopyrightText: 2021 Martin Häuer <martin.haeuer@ose-germany.de>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0" # NOT to be changed
name = "VentMon"
repo = "https://github.com/PubInv/ventmon-ventilator-inline-test-monitor"
version = "0.5"
# This needs to be a valid SPDX [License Expression](https://spdx.github.io/spdx-spec/v2-draft/SPDX-license-expressions/). Usually that is a single SPDX license ID, foudn in the "Identifier" column in this table: https://spdx.org/licenses/
license = "CERN-OHL-S-2.0"
licensor = "Robert Read <read.robert@gmail.com>"
function = "VentMon is an open source IoT-enabled spriometer for testing medical ventilators"
documentation-language = "en-US"
organization = "Public Invention"
release = "https://github.com/PubInv/ventmon-ventilator-inline-test-monitor/releases/tag/v0.3.1T"
readme = "https://github.com/PubInv/ventmon-ventilator-inline-test-monitor?tab=readme-ov-file"
contribution-guide = "https://github.com/PubInv/ventmon-ventilator-inline-test-monitor/graphs/contributors"
image = [
  # logo
  "imgs/11892727.png",
  # product-photo
  "imgs/244884512-b96dfc75-58e7-41bd-a88e-ea28e00b7dd8.jpg"
]
technology-readiness-level = "NA"
documentation-readiness-level = "NA"
attestation = "https://certification.oshwa.org/us002353.html"
publication = "https://www.sciencedirect.com/science/article/pii/S2468067221000249"
standard-compliance = "NA"
# A Cooperative Patent Classification-ID, describing this projects hardware; You may want to search for it here: <https://worldwide.espacenet.com/classification>
cpc-patent-class = "NA"
tsdc = "NA"
bom = "NA"
manufacturing-instructions = "https://github.com/PubInv/ventmon-ventilator-inline-test-monitor/tree/master/design/3dparts"
user-manual = "https://github.com/PubInv/vent-display"
# NOTICE: The below mass is a placeholder.
mass=1

[outer-dimensions]
width = "NA"
depth = "NA"
height = "NA"

[[part]]
name = "Shell or Housing? See scad."
image = "xxx.jpg"
tsdc = "NA"
source = "https://github.com/PubInv/ventmon-ventilator-inline-test-monitor/blob/master/design/3dparts/T0.5/VentMon0.5.scad"
export = [
  "xxx.pdf",
  "xxx.stl"
]
# NOTICE: The below mass is a placeholder.
mass=1

[part.outer-dimensions]
width = "NA"
depth = "NA"
height = "NA"

[[software]]
release = "https://github.com/PubInv/vent-display/releases/tag/v0.3T"
installation-guide = "https://github.com/PubInv/vent-display"

[[software]]
release = "https://github.com/PubInv/PIRDS-pubinv-respiration-data-standard/releases/tag/v1.3.0"
installation-guide = "https://github.com/PubInv/PIRDS-pubinv-respiration-data-standard"

[[software]]
release = "https://github.com/PubInv/PIRDS-logger/releases/tag/v0.3T"
installation-guide = "https://github.com/PubInv/PIRDS-logger"
# NOTICE: There are no releases for the below software.
[[software]]
release = "https://github.com/PubInv/PIRDS-docker-local/releases"
installation-guide = "https://github.com/PubInv/PIRDS-docker-local"
