# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "RKID-PAPR"
repo = "https://www.rkid.co.za/covid-19-industrial-design-innovation/?fbclid=IwAR2JYE70YHg-lB3fIALZFGJnk5XKVcOmlVnKa6YAs44H0GeF352klQAH4Lw"
license = "CC BY-SA 4.0"
licensor = "RKID <info@rkid.co.za>"
function = "Complete unit. Includes files for 3d printed air pump, cnc cuts for foam and poly facemask, requires P2 filters."
documentation-language = "en"
organization = "RKID"
readme = [
   "https://youtu.be/jFI6QTpyh0I",
   "https://youtu.be/nO74cnbN-lM",
   "https://www.rkid.co.za/portfolio/covid-19/"
]
image = [
  # logo
  "https://www.rkid.co.za/wp-content/uploads/2018/11/RKid-Logo-final-13nov18.png",
  # product-photo
  "https://www.rkid.co.za/wp-content/uploads/2020/04/CNC-routing-1024x456.jpg",
  "https://www.rkid.co.za/wp-content/uploads/2020/04/3D-printing-1024x456.jpg",
  "https://www.rkid.co.za/wp-content/uploads/2020/04/Dual-pipe-option-1024x469.jpg",
  "https://www.rkid.co.za/wp-content/uploads/2020/04/RKid_PARP_in_action.jpg"
]
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "A62B 7/10"
tsdc = "3DP" 
bom = [
   "https://www.rkid.co.za/wp-content/uploads/2020/04/RKid-3a-213x300.jpg",
   "https://www.rkid.co.za/wp-content/uploads/2020/04/RKid-3b-214x300.jpg",
   "https://www.rkid.co.za/wp-content/uploads/2020/04/RKid-3c-214x300.jpg"
]
manufacturing-instructions = "https://www.rkid.co.za/covid-19-industrial-design-innovation/?fbclid=IwAR2JYE70YHg-lB3fIALZFGJnk5XKVcOmlVnKa6YAs44H0GeF352klQAH4Lw"
user-manual = "https://youtu.be/HavZXC28sYU"
