# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "UW_Madison_PAPR-Hood_Only"
repo = "https://cms.delve.com/assets/documents/Badger-Shield-Open-Source-Hood-Drawing.pdf"
version = "7.0.0"
license = "CC-BY-4.0"
licensor = "Jesse Darley <JESSE.DARLEY@DELVE.COM>"
function = "Full set of PAPR, with a mantel, hood and a face shield. Template and sewing instructions are included."
documentation-language = "en-US"
organization = [
   "Delve",
   "University of Wisconsin-Madison"
]
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "A41D 13/11"
tsdc = "ASM"
bom = "https://cms.delve.com/assets/documents/Badger-Shield-Open-Source-Hood-Drawing.pdf"
manufacturing-instructions = "https://cms.delve.com/assets/documents/Badger-Shield-Open-Source-Hood-Drawing.pdfd"

[outer-dimensions]
# Dimensions of face shield. See manufacturing instructions to see dimensions of mantel and hood. Depth is a rough guess.
width = 342.9
depth = 101.6
height = 209.55
