# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Linda-Nguyen-Scrub-Hat"
repo = "https://drive.google.com/file/d/1c7lt-yts9RdMZbYBbAJPo3NzLwlV1sHl/view?fbclid=IwAR1UKZs3Sw9t7Tziv_Lf1AbsvyW7kqA0TYKm92Rzo6bb-yh3d8sMz-CtzIY"
license = "LicenseRef-NOASSERTION"
licensor = "Linda Nguyen <linda_nguyen_@hotmail.com>"
function = "Designed by a healthcare worker to contain long hair. Minimal elastic use."
documentation-language = "en"
organization = "Linda Nguyen"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "A41D 13/11"
# tsdc = "MEC/ASM/etc." 
manufacturing-instructions = "https://drive.google.com/file/d/1c7lt-yts9RdMZbYBbAJPo3NzLwlV1sHl/view?usp=sharing"
source = "https://drive.google.com/file/d/1J4NCaBCZDI4_IYO2RkZ8QXXHx0ONR0Cn/view?usp=sharing"

[outer-dimensions]
# Dimensions estimated from pattern.
width = 203.2
depth = 247.65
height = 177.8
