# SPDX-FileCopyrightText: 2024 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Badger-Shield:-Open-Source-Ophthalmologist-Face-Shield-V4"
repo = "https://drive.google.com/file/d/1sXRu7n665bt_uNaU4Dg6KnH2CTxvkAsh/view"
version = "1"
license = "NA"
licensor = "<kjwilliamso2@wisc.edu>"
function = "A single-use shield specifically made for ophthalmologist usage."
documentation-language = "en-US"
organization = [
  "The University of Wisconsin Makerspace",
  "Delve"
]
release = "v1 Initial Release / Keeler All Pupils II"
readme = "https://drive.google.com/file/d/1sXRu7n665bt_uNaU4Dg6KnH2CTxvkAsh/view"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-2"
cpc-patent-class = "A42B 3/00"
tsdc = "LAS" 
bom = "https://drive.google.com/file/d/1sXRu7n665bt_uNaU4Dg6KnH2CTxvkAsh/view"
manufacturing-instructions = "https://drive.google.com/file/d/1sXRu7n665bt_uNaU4Dg6KnH2CTxvkAsh/view"
source = "https://www.mcmaster.com/8567k64"

[outer-dimensions]
width = "304.8"
height = "323.85"
