# SPDX-FileCopyrightText: 2024 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0" 
name = "Badger-Shield:-Open-Source-Face-Shield-V4"
repo = "https://www.delve.com/insights/face-shield-designs-to-fill-the-gap"
version = "4"
license = "Not applicable."
licensor = "Jesse Darley <JESSE.DARLEY@DELVE.COM>"
function = "COVID-19 Medical Face Shield (University of Wisconsin)"
documentation-language = "en-US"
organization = "Delve"
release = "https://cms.delve.com/assets/documents/OPEN-SOURCE-FACE-SHIELD-DRAWING-v1.PDF"
# readme = "https://cms.delve.com/assets/documents/OPEN-SOURCE-FACE-SHIELD-DRAWING-v1.PDF"
image = [
  # product-photo
  "https://www.delve.com/_next/image?url=https%3A%2F%2Fcms.delve.com%2Fassets%2Fimages%2FFace-Shield-on-Mannikin-for-Banner.jpg&w=1920&q=75",
  "https://www.delve.com/_next/image?url=https%3A%2F%2Fcms.delve.com%2Fassets%2Fimages%2FFace-Shield-on-Jesse.jpg&w=1920&q=75",
  "https://www.delve.com/_next/image?url=https%3A%2F%2Fcms.delve.com%2Fassets%2Fimages%2FFace-Shield-Packaged-Rotated.jpg&w=1920&q=75"
]
technology-readiness-level = "OTRL-5"
documentation-readiness-level = "ODRL-3"
# standard-compliance = Does not meet license criteria, none listed.
cpc-patent-class = "A42"
# tsdc = "ASM"
bom = "https://cms.delve.com/assets/documents/OPEN-SOURCE-FACE-SHIELD-DRAWING-v1.PDF"
manufacturing-instructions = "https://cms.delve.com/assets/documents/OPEN-SOURCE-FACE-SHIELD-DRAWING-v1.PDF"

[outer-dimensions]
width = "330.20"
height = "228.60"

[[Parts-source]]
source = "https://cms.delve.com/assets/documents/OPEN-SOURCE-FACE-SHIELD-DRAWING-v1.PDF"
