# SPDX-FileCopyrightText: 2024 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "DtM_Face_Shield_Headband"
repo = "https://3d.nih.gov/entries/3dpx-013359"
version = "3.1"
license = "Public Domain"
licensor = [
   "Elizabeth Johnson <elizabeth.johansen@olin.edu>",
   "David Packman",
   "Eric Moyer"
]
function = "This PPE is designed specifically for the needs of healthcare workers during the COVID-19 pandemic. It reduces aerosol and splatter exposure and can undergo multiple reuses and cleanings. Additionally, the mask is comfortable and provides ventilation for all-day wear."
documentation-language = "en-US"
organization = "xxx"
# In the case of no releases, can link to the latest commit.
release = "https://gitlab.com/YOU/your-awesome-project/-/releases/1.0.0"
readme = "README.md"
contribution-guide = "CONTRIBUTING.md"
image = [
  # logo
  "imgs/xxx.jpg",
  # product-photo
  "imgs/yyy.jpg"
]
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
attestation = "https://certification.oshwa.org/cl000001.html"
publication = "https://doi.org/10.1371/journal.pone.0193087"
# A Cooperative Patent Classification-ID, describing this projects hardware; You may want to search for it here: <https://worldwide.espacenet.com/classification>
cpc-patent-class = "D03D 35/00"
bom = "BoM.csv"
manufacturing-instructions = "Documentation/Assembly_Guide/AssemblyGuide.md"
user-manual = "Documentation/User_Guide/UserGuide.md"
# Sources for the parts information
source = [
     "main.scad",
     "part_a.scad",
     "part_b.scad",
     "params.csv"
     ]
# Any mass always has to be in g (gramms)
mass= 50330.0

[outer-dimensions]
# Any dimension value always has to be in [mm] (milli-meters)
width = "400"
depth = "350"
height = "150"

[[software]]
release = "https://github.com/arduino/ArduinoCore-mbed/releases/tag/1.3.2"
installation-guide = "https://github.com/arduino/ArduinoCore-mbed/blob/a2c06d768f5ebb6821ae6505b2032ee58f4ef70d/README.md"
