# SPDX-FileCopyrightText: 2024 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0" 
name = "FDS_PAPR"
repo = "https://www.instructables.com/DIY-Powered-Air-Purifying-Respirator-PAPR/"
version = "1.0.0"
license = "CC-BY-NC-SA-4.0"
licensor = "Nathan de Souza <njds337@gmail.com>"
function = "This device is a lightweight powered air-purifying respirator (PAPR) that provides filtered air, face and eye protection, and skin surface cooling."
documentation-language = "en-au"
organization = "Autodesk Instructables"
# release = "https://gitlab.com/YOU/your-project/-/releases/1.0.0"
# readme = "README.md"
# contribution-guide = "CONTRIBUTING.md"
image = [
  # product-photo
  "https://content.instructables.com/FVA/WNDF/LILYUDDY/FVAWNDFLILYUDDY.png",
  # product-photo
  "https://content.instructables.com/FBQ/O9NK/LEE9CN58/FBQO9NKLEE9CN58.png",
  # product-photo
  "https://content.instructables.com/FKI/LHY5/LEE9CN57/FKILHY5LEE9CN57.jpg"
]
technology-readiness-level = "OTRL-5"
documentation-readiness-level = "ODRL-3"
# attestation = "NA"
publication = "https://www.instructables.com/DIY-Powered-Air-Purifying-Respirator-PAPR/"
# standard-compliance = "Not sure"
cpc-patent-class = "A42"
# tsdc = "Need further instruction"
bom = "Cost+of+Materials+11-05-2023.pdf"
manufacturing-instructions = "Documentation/Assembly_Guide/AssemblyGuide.md"
user-manual = "PAPR+Design+Report+2023.pdf"
mass= 220

[outer-dimensions]
width = "170"
height = "240"
depth = "210"


[[part]]
name = "Visor"
image = "https://content.instructables.com/F8W/EFNQ/LEFOW28D/F8WEFNQLEFOW28D.jpg"
# tsdc = "Not sure"
source = "Visor_Template_mm.pdf"
export = [
  "https://content.instructables.com/FT3/5A1W/LEE9COVQ/FT35A1WLEE9COVQ.jpg",
  "https://content.instructables.com/F1Q/XL1T/LEE9COVU/F1QXL1TLEE9COVU.jpg",
  "https://content.instructables.com/FT8/7UWP/LEE9COVV/FT87UWPLEE9COVV.jpg",
  "https://content.instructables.com/F5I/7EZ5/LEE9COW1/F5I7EZ5LEE9COW1.jpg"
]

[part.outer-dimensions]
width = "135"
height = "240"
