# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Ebin-CPAP-Adapter"
repo = "https://drive.google.com/file/d/1Tli-Pm7Z7Ni7OwgPLBuvH2rL106SWzR0/view?usp=sharing"
version = "1.0.0"
license = "LicenseRef-NOASSERTION"
licensor = "Jeffrey Ebin <https://www.youtube.com/@DrJeff->"
function = "Physician designed modification for a CPAP or BiPAP mask. This 3DP adapter permits a viral filter connection which limits COVID-19 aerosolization. View the testing documentation for expiratory pressure data."
documentation-language = "en"
organization = "Jeffey Ebin"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "A62B 9/022"
tsdc = "3DP" 
manufacturing-instructions = "https://drive.google.com/file/d/1Tli-Pm7Z7Ni7OwgPLBuvH2rL106SWzR0/view"
source = "https://drive.google.com/file/d/1Tn4A17ci4_tWdbc35ut588XaICljRZDv/view?usp=sharing"
