# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "NJIT-Throat-Swab"
repo = "https://3dprint.nih.gov/discover/3dpx-014187"
version = "2.0.0"
license = "CC-BY-4.0"
licensor = "New Jersey Institute of Technology <njitaddlab@gmail.com>"
function = "PLA-printed throat swab using sterile rayon fabric as collection material."
documentation-language = "en-US"
organization = "New Jersey Institute of Technology"
contribution-guide = "https://3d.nih.gov/entries/3DPX-014187#attribution"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
publication = "https://news.njit.edu/njit-physics-team-provides-novel-swab-design-free-charge-augment-covid-19-testing"
cpc-patent-class = "A61B 1/00"
tsdc = "3DP"
bom = "https://3d.nih.gov/entries/3DPX-014187#printing"
manufacturing-instructions = "https://3d.nih.gov/entries/3DPX-014187#printing"
source = [
     "https://3d.nih.gov/entries/download/14187/2",
     "https://3d.nih.gov/api/submissions/18518/files/input/567636?/UM3_NJIT_SWAB.gcode",
     "https://3d.nih.gov/api/submissions/18518/files/input/401367",
     "https://3d.nih.gov/api/submissions/18518/files/input/401371",
     "https://3d.nih.gov/api/submissions/18518/files/input/401370",
     "https://3d.nih.gov/api/submissions/18518/files/input/401377",
     "https://3d.nih.gov/api/submissions/18518/files/input/401378",
     "https://3d.nih.gov/api/submissions/18518/files/input/401380",
     "https://3d.nih.gov/api/submissions/18518/files/input/567636"
]

[[image]]
location = "https://www.njit.edu/"
slots = [
  "logo",
]
tags = [
  "logo",
]

[[image]]
location = "https://3d.nih.gov/api/submissions/18518/files/input/401362"
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]

[[image]]
location = "https://3d.nih.gov/api/submissions/18518/files/input/401368"

[[image]]
location = "https://3d.nih.gov/api/submissions/18518/files/input/401369"

[[image]]
location = "https://3d.nih.gov/api/submissions/18518/files/input/401376"

[[image]]
location = "https://3d.nih.gov/api/submissions/18518/files/input/401379"

[[image]]
location = "https://3d.nih.gov/api/submissions/18518/files/input/401374"
