# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "2.4"
name = "Matamoros-Hand-Washing-Station"
repo = "https://www.youtube.com/watch?v=0iPawutpe9Q"
license = "LicenseRef-NOASSERTION"
licensor = "Resource Center of Matamoros <https://www.youtube.com/@resourcecenterofmatamoros7089>"
function = "This thing can clean, fly to the moon, keep you warm when its freezing, transplant an organ on its own, ..."
documentation-language = "en"
version = "1.0.0"
organization = "Resource Center of Matamoros"
technology-readiness-level = "OTRL-1"
documentation-readiness-level = "ODRL-1"
cpc-patent-class = "C11D 17/00"
tsdc = "ASM"
bom = "https://www.youtube.com/watch?v=0iPawutpe9Q"
manufacturing-instructions = "https://www.youtube.com/watch?v=0iPawutpe9Q"

[[image]]
location = "https://yt3.googleusercontent.com/ytc/AIdro_nyrBSFPogy8ZtW9A9FR0JdlvlDvCQbpWBUPSP7z3efVA=s160-c-k-c0x00ffffff-no-rj"
depicts = "The logo of the Resource Center of Matamoros."
slots = [
  "logo",
]
tags = [
  "logo",
]

[[image]]
location = "https://cdn.prod.website-files.com/679bd6d8e9c2f7d8d67ee78a/67be8a120017412668117d22_67b4e900e2177ffe3d65189f_Screen%2520Shot%25202020-05-10%2520at%252012.06.07%2520AM.png"
depicts = "Main photo of Matamoros Hand Washing Station."
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]
