# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "2.4"
name = "Badger-Seal-Mask-Fitter"
repo = "https://www.youtube.com/watch?v=0CSZrCUAm3g"
license = "LicenseRef-NOASSERTION"
licensor = "Lennon Rodgers <https://www.youtube.com/@LennonRodgers>"
function = "This comfortable mask fitter is versatile to many wearing preferences. It can be made with simple household tools and materials easily sourced from a local hardware store."
documentation-language = "en"
version = "1.0.0"
organization = "University of Wisconsin-Madison"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-2"
cpc-patent-class = "A41D 13/11"
tsdc = "ASM"
bom = "https://docs.google.com/presentation/d/1bTUmxEiZ_EMo9DYjHWl13rarzPwKDukUQhRj-gxJxfM/edit?slide=id.g93821f08fa_55_6#slide=id.g93821f08fa_55_6"
manufacturing-instructions = "https://www.youtube.com/watch?v=0CSZrCUAm3g"
source = "https://drive.google.com/file/d/148BA4oEI6kMx3x9GDs3XVsi2CEk-C4al/view"

[[image]]
location = "https://cdn.prod.website-files.com/679bd6d8e9c2f7d8d67ee78a/67be8ae09a8e5c908ec95050_67b4e8beaa243789d41dfba6_BADGER.jpeg"
depicts = "Badger Seal Mask Fitter main photo."
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]
