# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "2.4"
name = "M19O2"
repo = "https://github.com/MakersAsylumIndia/M19O2"
version = "3.0.0"
license = "CC-BY-4.0"
licensor = "Maker's Asylum <info@makersasylum.com>"
function = "Oxygen Concentrator based on the Pressure Swing Absorption cycle aka Skarstrom cycle and designed to operate in high humidity conditions, such as western India."
documentation-language = "en"
organization = "Maker's Asylum"
release = "https://github.com/MakersAsylumIndia/M19O2/commit/19fe5d6db049e2199ca5744df195c1c65db2c71a"
readme = "https://github.com/MakersAsylumIndia/M19O2/blob/main/README.md"
contribution-guide = "https://github.com/MakersAsylumIndia/M19O2/graphs/contributors"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
attestation = "https://certification.oshwa.org/in000029.html"
cpc-patent-class = "F25J 3/0625"
tsdc = "ASM"
bom = "https://github.com/MakersAsylumIndia/M19O2/tree/main/BoM_datasheets"
manufacturing-instructions = [
   "https://github.com/MakersAsylumIndia/M19O2/blob/main/docs/M19O2%20-%20Assembly%20Manual.pdf",
   "https://github.com/MakersAsylumIndia/M19O2/blob/main/docs/M19O2%20-%20Instruction%20Manual.pdf"
]
user-manual = "https://github.com/MakersAsylumIndia/M19O2/blob/main/docs/M19O2%20-%20Data%20sheet.pdf"
source = [
     "https://github.com/MakersAsylumIndia/M19O2/tree/main/deployment",
     "https://github.com/MakersAsylumIndia/M19O2/tree/main/docs",
     "https://github.com/MakersAsylumIndia/M19O2/tree/main/engineering",
     "https://github.com/MakersAsylumIndia/M19O2/tree/main/renders"
]

[[image]]
location = "https://avatars.githubusercontent.com/u/9796280?s=48&v=4"
slots = [
  "logo",
]
tags = [
  "logo",
]

[[image]]
location = "https://raw.githubusercontent.com/MakersAsylumIndia/M19O2/19fe5d6db049e2199ca5744df195c1c65db2c71a/images/M19O2%20logo.svg"

[[image]]
location = "https://github.com/MakersAsylumIndia/M19O2/blob/main/images/M19collective_logo_01.jpeg?raw=true"

[[image]]
location = "https://github.com/MakersAsylumIndia/M19O2/raw/main/renders/M19O2_v4_08.png"
slots = [
  "photo-thing-main",
]
tags = [
  "photo",
]

[[image]]
location = "https://github.com/MakersAsylumIndia/M19O2/raw/main/renders/M19O2_v4_06.png"

[[image]]
location = "https://github.com/MakersAsylumIndia/M19O2/raw/main/renders/M19O2_v4_07.png"

[[image]]
location = "https://github.com/MakersAsylumIndia/M19O2/blob/main/images/M19O2_clear.jpg?raw=true"

[[image]]
location = "https://github.com/MakersAsylumIndia/M19O2/blob/main/images/m19o2_V4-04%20no%20bg.png?raw=true"

[[image]]
location = "https://github.com/MakersAsylumIndia/M19O2/blob/main/images/m19o2_V4-04-removebg-preview.png?raw=true"

[[image]]
location = "https://github.com/MakersAsylumIndia/M19O2/blob/main/images/m19o2_V4-04.jpg?raw=true"

[[image]]
location = "https://github.com/MakersAsylumIndia/M19O2/blob/main/images/m19o2_V4-08.jpg?raw=true"

[[image]]
location = "https://github.com/MakersAsylumIndia/M19O2/blob/main/images/m19o2_V4-18.jpg?raw=true"
