# SPDX-FileCopyrightText: 2025 Mairin O'Grady <mogrady@udallas.edu>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "OKH-LOSHv1.0"
name = "Public-Invention/Ox"
repo = "https://github.com/PubInv/Ox"
version = "1.0.0"
license = "GPL-3.0-only"
licensor = "Robert Read <read.robert@gmail.com>"
function = "Oxygen concentrator designed for local manufacturing in low-resource communities, addressing issues such as high humidity and temperature, dust, and restricted technology access."
documentation-language = "en-US"
organization = "Public Invention"
release = "https://github.com/PubInv/Ox/commit/751568cced500a0659e9dff345946a4bf13eea54"
readme = "https://github.com/PubInv/Ox/blob/develop/README.md"
contribution-guide = "https://github.com/PubInv/Ox/graphs/contributors"
image = [
  # logo
  "https://avatars.githubusercontent.com/u/11892727?s=48&v=4",
  # product-photo
  "https://github.com/PubInv/Ox/blob/develop/docs/img/concept_sketch.jpg",
  "https://github.com/PubInv/Ox/blob/develop/docs/img/intercooler.jpg",
  "https://github.com/PubInv/Ox/blob/develop/docs/img/pioc-build-001.jpg",
  "https://github.com/PubInv/Ox/blob/develop/docs/img/pioc-build-002.jpg",
  "https://github.com/PubInv/Ox/blob/develop/docs/img/pioc-mockup.jpg",
  "https://github.com/PubInv/Ox/blob/develop/docs/img/pioc_circuit.jpg",
  "https://github.com/PubInv/Ox/blob/develop/docs/img/pioc_firstrun.jpg",
  "https://github.com/PubInv/Ox/blob/develop/docs/img/pneumatic_circuit_prototype_v1.jpg",
  "https://github.com/PubInv/Ox/blob/develop/docs/img/pneumatic_circuit_sketch.jpg",
  "https://github.com/PubInv/Ox/blob/develop/docs/img/pneumatic_circuit_wall_mounted.jpg",
  "https://github.com/PubInv/Ox/blob/develop/docs/img/valve_contamination.jpg",
  "https://github.com/PubInv/Ox/blob/develop/docs/img/ventmon95o2.jpg",
  "https://github.com/PubInv/Ox/blob/develop/docs/img/ventmonadaptor.jpg"
]
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
cpc-patent-class = "F25J 3/0625"
tsdc = "MEC" 
bom = [
   "https://github.com/PubInv/Ox/blob/develop/bom/PIOC_bom.xlsx",
   "https://github.com/PubInv/Ox/blob/develop/bom/bill_of_materials.md"
]
manufacturing-instructions = [
   "https://github.com/PubInv/Ox/tree/develop/RS232-powersupply",
   "https://github.com/PubInv/Ox/tree/develop/elec",
   "https://github.com/PubInv/Ox/tree/develop/fancontroller",
   "https://github.com/PubInv/Ox/tree/develop/firmware",
   "https://github.com/PubInv/Ox/tree/develop/mech"
]
